### ISSUE TITLE
mc rm doesn't remove files by prefix as per the inline documents

### ISSUE THREAD

**Issue by khumps** [minio/mc#2968] opened 2019-11-22 13:37 UTC
## Expected behavior
`mc rm clustername/testbucket/test/` should remove all files that start with the prefix `test` from the bucket `clustername/testbucket/`
## Actual behavior
`mc: <ERROR> Failed to remove clustername/testbucket/test/. Target object is not found`
## Steps to reproduce the behavior

1. create a bunch of files with the same prefix in a bucket
2. try to remove them using `mc rm clustername/bucketname/prefix/`
3. get an error that they don't exist

## mc version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e

**Comment by harshavardhana** [comment] 2019-11-22 19:32
You need to use `mc rm -r` to recurse a prefix this is working as expected @khumps

**Comment by khumps** [comment] 2019-11-22 19:41
ah I see, so that extra `/` after test shouldn't be there it seems.  that extra `/` makes it search inside of the bucket `test` not files named `test*`

**Comment by harshavardhana** [comment] 2019-11-22 20:33
Closing this with working as intended

**Closed by harshavardhana** 2019-11-22 20:33 UTC
Labels: working as intended
