### ISSUE TITLE
mirror with --watch parameter: "Unable to list comparison retrying.. XML syntax error on line 2: expected attribute name in element"

### ISSUE THREAD

**Issue by 4001982248998** [minio/mc#3589] opened 2021-01-27 09:56 UTC
While possible to copy files and also starting to mirror a directory to a bucket, mc fails to mirror with ``--watch`` parameter, throwing the following error:

```
Unable to list comparison retrying.. XML syntax error on line 2: expected attribute name in element
```

## Expected Behavior
mc should mirror the directory and "watch" it.

## Current Behavior
mc is not mirroring the directory, but instead looping an error message "XML syntax error on line 2: expected attribute name in element".

## Possible Solution
If there are issues with any files or whatever the reason is to be unable to mirror, it should point me to the problem.

## Steps to Reproduce (for bugs)

For me: ``mc mirror --watch /data myminio/backup``

## Context
Trying to backup user files to a Minio server.

## Regression
Yes. Backups do not work, and problem cannot fixed without knowing the reason.

## Your Environment
* Version used (`minio --version`):
  * Server: minio version RELEASE.2021-01-16T02-19-44Z
  * Client: mc version RELEASE.2021-01-16T02-45-34Z
* Server setup and configuration: Minio cluster consisting of 8 nodes
* Operating System and version (`uname -a`):
  * Server:
    * Linux fnf-minio-08 5.4.0-64-generic minio/minio#72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    * Ubuntu 20.04.1 LTS
  * Client:
    * Linux FNF-Host-MM-YA 4.15.0-134-generic minio/minio#138-Ubuntu SMP Fri Jan 15 10:52:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    * Ubuntu 18.04.5 LTS

**Comment by 4001982248998** [comment] 2021-01-28 06:59
No, only a tcp port redirection by firewalld, redirecting incoming 443/tcp to minio's local 9000/tcp.

**Comment by harshavardhana** [comment] 2021-01-28 07:01
> No, only a tcp port redirection by firewalld, redirecting incoming 443/tcp to minio's local 9000/tcp.

Please share `mc mirror --debug`

**Comment by 4001982248998** [comment] 2021-01-28 12:56
Please find the resulting output as attached file. I have replaced the names of the two hosts, source/destination directory and bucket names.

[mc-debug.log](https://github.com/minio/mc/files/5887234/mc-debug.log)

**Comment by ebozduman** [comment] 2021-04-18 08:52
@4001982248998,

We need a little bit more information as we cannot reproduce the issue here locally.

Like:
- What is the exact command used, when the bucket, `mybucket`, was created?
(bucket name is from your debug file.
Was it created with `--with-lock` flag, and if so, was versioning enabled, which is by default, or was it suspended at some point; any locks on any objects in your bucket before mirroring was started?

- What type of files/objects were on both sides, at `/mydatadir/` and at `myminioserver/mybucket/mybackupdir/]` when mirroring was started, average size of the data, what kinds of data, maximum and minimum sizes of filea/objects, how many total objects/files, overall data size that is mirrored, etc.

**Comment by ebozduman** [comment] 2021-04-22 16:37
@4001982248998,
Closing this issue as we cannot reproduce it.
If there is more information on how we can reproduce it, please reopen the issue and let us know.

**Closed by ebozduman** 2021-04-22 16:37 UTC
Labels: community, incomplete-info
