### ISSUE TITLE
duplicated notification configuration when running `mc events add`

### ISSUE THREAD

**Issue by balamurugana** [minio/mc#2324] opened 2017-12-05 16:31 UTC
## Expected behaviour
Should not send duplicate queue configuration.

## Actual behaviour
Duplicate queue configuration is sent.

## Steps to reproduce the behaviour
Run below steps
1. After running `mc events remove local/mybucket --force`, server has below XML
```xml
<NotificationConfiguration/>
```

2. After running `mc events add local/mybucket arn:minio:sqs::1:webhook`, server has below XML
```xml
<NotificationConfiguration>
  <QueueConfiguration>
    <Id/>
    <Filter>
      <S3Key/>
    </Filter>
    <Event>s3:ObjectCreated:*</Event>
    <Event>s3:ObjectRemoved:*</Event>
    <Event>s3:ObjectAccessed:*</Event>
    <Queue>arn:minio:sqs::1:webhook</Queue>
  </QueueConfiguration>
</NotificationConfiguration>
```

3. Repeating above step leads to below XML
```xml
<NotificationConfiguration>
  <QueueConfiguration>
    <Id/>
    <Filter>
      <S3Key/>
    </Filter>
    <Event>s3:ObjectCreated:*</Event>
    <Event>s3:ObjectRemoved:*</Event>
    <Event>s3:ObjectAccessed:*</Event>
    <Queue>arn:minio:sqs::1:webhook</Queue>
  </QueueConfiguration>
  <QueueConfiguration>
    <Id/>
    <Filter>
      <S3Key/>
    </Filter>
    <Event>s3:ObjectCreated:*</Event>
    <Event>s3:ObjectRemoved:*</Event>
    <Event>s3:ObjectAccessed:*</Event>
    <Queue>arn:minio:sqs::1:webhook</Queue>
  </QueueConfiguration>
</NotificationConfiguration>
```
## mc version
- (paste output of `mc version`)
```
Version: 2017-12-05T10:30:49Z
Release-tag: DEVELOPMENT.2017-12-05T10-30-49Z
Commit-id: 1fd03fb81fd192c1b01846a1b796135249003552
```

**Comment by harshavardhana** [comment] 2017-12-07 20:53
Shouldn't this be a minio-go bug @balamurugana ?

**Comment by balamurugana** [comment] 2017-12-08 02:33
@harshavardhana I haven't traced the issue.  Assignee needs to trace and act accordingly.

**Comment by kannappanr** [comment] 2017-12-11 22:00
@balamurugana , I am unable to reproduce the issue here.

mc verison output
```
Version: 2017-12-11T21:46:05Z
Release-tag: DEVELOPMENT.2017-12-11T21-46-05Z
Commit-id: 5ddf9728f87e0a0203ab24bdc8d390addfd7175a
```
The minio version used was 

```
Version: 2017-11-17T22:59:01Z
Release-Tag: RELEASE.2017-11-17T22-59-01Z
Commit-ID: b97f99766f46c5ecf285503766a2c182ea8b35c1
```

and 

```
Version: 2017-12-11T07:25:12Z
Release-Tag: DEVELOPMENT.2017-12-11T07-25-12Z
Commit-ID: d4c22901f3e14519a1e998cce3781b49861f95cd

```

Config.json had the following setting for webhooks

```
"webhook": {
			"1": {
				"enable": true,
				"endpoint": "http://localhost:8000"
			}
		},
```
The notifications.xml file on the server for the test bucket after step 1 is
```
<NotificationConfiguration></NotificationConfiguration>
```
After step 2, it is 
```
<NotificationConfiguration><QueueConfiguration><Event>s3:ObjectCreated:*</Event><Event>s3:ObjectRemoved:*</Event><Event>s3:ObjectAccessed:*</Event><Filter><S3Key></S3Key></Filter><Id></Id><Queue>arn:minio:sqs::1:webhook</Queue></QueueConfiguration></NotificationConfiguration>
```

If I repeat Step 2, I get the following error on the console.

``` 
mc: <ERROR> Cannot enable notification on the specified bucket. Configurations overlap. Configurations on the same bucket cannot share a common event type.
```

If I repeat Step 1 and Step 2, everything is fine.

Can you explain more as to how I can reproduce the issue you are seeing?

**Comment by balamurugana** [comment] 2017-12-12 01:50
@kannappanr 
> If I repeat Step 2, I get the following error on the console.

Yes.  You are getting this, because `mc` sends repeated queue configuration mentioned in the description.  The issue here is `mc` should not send wrong XML to server.

**Comment by kannappanr** [comment] 2018-02-25 06:36
The PR previously referenced had the required fix in minio-go. The corresponding mc fix required to solve this issue is #2402, so re-opening the issue

**Comment by nitisht** [comment] 2018-02-26 18:36
Closed by mistake, reopening

**Comment by harshavardhana** [comment] 2018-02-26 18:49
a good test case for mint as well i guess?

**Closed** 2018-02-26 22:28 UTC
Labels: priority: medium
