### ISSUE TITLE
minio cp does not work as expected for local files on windows

### ISSUE THREAD

**Issue by lookingcloudy** [minio/mc#2295] opened 2017-10-24 19:03 UTC
## Expected behaviour
Should recursively copy all the files and subdirectories to the target location.

## Actual behaviour
The progress bar shows the source files flashing by as if they are copying.  The files are not copied to the target location.  I cannot identify where (if) the files are copied.

## Steps to reproduce the behaviour
mc cp --recursive --parallel=10 d:\mydir\ z:\copy-dir
Where, z:= mapped drive to another computer on the LAN (\\10.10.10.10\d$)

I have also tried to copy to a test folder on the same drive, with the same result:
mc cp --recursive d:\mydir\ d:\mytestdir

mc mirror works as expected, however is very slow due to single thread serial copy.

## mc version
- (paste output of `mc version`)
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195

## System information
Windows 2016

**Comment by poornas** [comment] 2017-10-26 01:31
@lookingcloudy , could you run this command with --json option and check the success status and target destination of the files that failed to copy?
```mc cp --recursive --json d:\mydir\ d:\mytestdir```

**Comment by deekoder** [comment] 2017-10-31 21:00
@lookingcloudy  we are closing this issue. feel free to reopen if you think the issue is not resolved.

**Closed by deekoder** 2017-10-31 21:00 UTC
Labels: priority: medium, triage, working as intended
