### ISSUE TITLE
mc mirror does not mirror empty directories

### ISSUE THREAD

**Issue by arno01** [minio/mc#2612] opened 2018-11-23 10:12 UTC
mc mirror does not mirror empty directories

```
$ mc version
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511
$ mkdir -p source/{1,2,3} target/
$ ls -la source/
total 20
drwxr-xr-x 5 user user 4096 Nov 23 11:10 .
drwxr-xr-x 4 user user 4096 Nov 23 11:10 ..
drwxr-xr-x 2 user user 4096 Nov 23 11:10 1
drwxr-xr-x 2 user user 4096 Nov 23 11:10 2
drwxr-xr-x 2 user user 4096 Nov 23 11:10 3
$ mc mirror --remove source/ target/
 0 B / ? ┃░░░░░░░░▓┃ 0s
$ ls -la target/
total 8
drwxr-xr-x 2 user user 4096 Nov 23 11:10 .
drwxr-xr-x 4 user user 4096 Nov 23 11:10 ..
$ 
```

Is this expected?

**Comment by harshavardhana** [comment] 2018-11-23 19:04
This is simply a matter of choice,  it is discouraged creating empty directories - they are frivolous operation on Object Storage. Since object storage is a flat namespace it is better to create a namespace entry when there is an object rather than having a list of empty directories which are practically not useful.  `mc mirror` with these requirements in mind.

**Comment by deekoder** [comment] 2018-11-28 02:13
@arno01 since this behavior is by design, I am closing this issue. Please reopen if you feel strongly that this case needs to be handled with any additional datapoints.

**Closed by deekoder** 2018-11-28 02:13 UTC
Labels: community, priority: medium, working as intended
