### ISSUE TITLE
mc cp selective local files not working

### ISSUE THREAD

**Issue by miketheknife** [minio/mc#2766] opened 2019-05-02 16:51 UTC
## Expected behavior
Copy selective from local filesystem for remote minio instance

## Actual behavior
Getting error message 
"Unable to validate source C:\Users\mike\Documents\meshmixer\autosave\\*.mix"

## Steps to reproduce the behavior
mc cp  C:\Users\mike\Documents\meshmixer\autosave\\*.mix mynfs/random

- I can list the local files in the directory using "mc ls"
mc ls C:\Users\mike\Documents\meshmixer\autosave
[2018-01-26 17:23:22 CET]  241KiB autosave_29964_2018-01-26_17_23_22.mix

- I can copy the wohle directory using no asterisk and the --recursive flag

## mc version
Version: 2019-05-01T23:27:44Z
Release-tag: RELEASE.2019-05-01T23-27-44Z
Commit-id: b1aa2232ef3babc5f06bacb1b0044022185457ca

## System information
Windows 10 / 64

**Comment by kannappanr** [comment] 2019-05-02 20:41
@miketheknife Thanks for filing this issue. We will take a look at it.

**Comment by sinhaashish** [comment] 2019-05-06 07:25
@miketheknife  This perfectly works fine with Linux, Will check with windows box and update.

**Comment by sinhaashish** [comment] 2019-10-07 11:18
Printing the `os.Args` in the `main.go` on  Unix and windows respectively 
```
import (
	"fmt"
	"os"
)

func main() {
	fmt.Println( os.Args)
      //mc.Main(os.Args)
```
Unix
```
ashish@minio:~/code/go/src/github.com/minio/mc$ go build main.go 
ashish@minio:~/code/go/src/github.com/minio/mc$ ./main  ls *.md
```
Unix O/P 
```
[./main ls CONFLICT.md CONTRIBUTING.md README.md README_zh_CN.md]
```
Windows :
```
C:\Users\golang\src\github.com\minio\mc > go run main.go
C:\Users\golang\src\github.com\minio\mc > main.exe ls *.md
```
Windows O/P :
```
[main.exe ls *.md] 
```

In Windows the wild card doesn't work for `os.Args` . This is the root cause of the issue.  Can make Windows specific change if agreed.

**Comment by harshavardhana** [comment] 2020-01-20 09:36
> In Windows the wild card doesn't work for `os.Args` . This is the root cause of the issue.

Closing this as wildcards are not supported on Windows

**Closed by harshavardhana** 2020-01-20 09:36 UTC
Labels: community, priority: medium
