### ISSUE TITLE
missing SSE-S3 support ("--sse" option) to upload objects to S3 buckets 

### ISSUE THREAD

**Issue by robert-mcdermott** [minio/mc#2256] opened 2017-09-21 19:34 UTC
## Expected behaviour

'mc' should have the ability to tell S3 to use SSE (server side encryption) when uploading objects. We have an S3 bucket policy that enforces that all uploaded objects use SSE-S3 (--sse AES256) and we are unable to use 'mc' at this time (but would like to). It should work like this:

```
mc cp --sse file.txt s3/file.txt 
```

## Actual behaviour

Without this flag we receive an "access denied" error from S3

## Steps to reproduce the behaviour

Attempt upload a file to an S3 bucket that has a bucket policy enforcing SSE on putObject.

## mc version
- (paste output of `mc version`)

Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4

## System information

Ubuntu 16.04 x86_64 (Linux 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by aead** [comment] 2017-09-21 20:52
Hi @robert-mcdermott 
I'm currently working on the encryption support minio server SSE-C, minio-go client/server side encryption support and also mc. Your request is on our todo list, thanks for the report.
Will keep you updated.

**Comment by deekoder** [comment] 2017-09-22 20:55
Putting this in future since we are working on this.

**Comment by harshavardhana** [comment] 2018-02-21 00:26
Closing as duplicate of #2074

**Closed by harshavardhana** 2018-02-21 00:26 UTC
Labels: priority: medium
