### ISSUE TITLE
failed to execute cp -r and ls -r on a bucket

### ISSUE THREAD

**Issue by mohamedzayan19** [minio/mc#3085] opened 2020-02-18 14:13 UTC
Executed cp -r on a non empty bucket with 5 files. 
Riak cluster.
minio client github latest version, and linux latest version both tried
## Expected behavior
 files expected to be downloaded to my machine
## Actual behavior
main: <ERROR> Unable to list folder. Get http://192.168.178.24:8080/ossperf-testbucket/?delimiter=&max-keys=1000&prefix=: Connection closed by foreign host http://192.168.178.24:8080/ossperf-testbucket/?delimiter=&max-keys=1000&prefix=. Retry again.
## Steps to reproduce the behavior
Create a bucket.
Put 5 files inside the bucket.
call mc cp -r or mc ls -r

## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-02-14T19-35-50Z
## System information
Ubuntu 16.04

After some research, the error is possibly due to an incorrect delimiter being passed to the cluster.
particularly "delimiter=". Is there a way around this? I will be ok if i am just able to hardcode it somewhere.

**Comment by harshavardhana** [comment] 2020-02-18 14:52
This has nothing to do with incorrect Delimiter, as the error message indicates it's your network connection issue.

**Comment by mohamedzayan19** [comment] 2020-02-18 14:57
Well actually, when I am doing a normal ls, it is working fine. So , I guess it is not network related.
I also inspected the logs of my cluster nodes, 

CRASH REPORT Process <0.6259.1> with 1 neighbours exited with reason: bad argument in call to binary:match(<<"ossperf-testfile1.txt">>, [<<>>]) in riak_cs_list_objects_utils:extract_group/2 line 197

It is actually crashing. I looked up the issue on their mailing lists, someone had the exact same error, which was due to an incorrect delimiter. 

One more thing I inspected the http request sent when listing normally vs recursively
The request with the normal ls
GET /buckets/ossperf-testbucket/objects?prefix&list-type=2&fetch-owner=true&encoding-type=url&delimiter=%2F HTTP/1.1" 200 1917 "" "MinIO (linux; amd64) minio-go/v6.0.45 mc/2020-02-05T20:07:22Z"

which works perfectly fine,and does contain a working delimiter

**Comment by harshavardhana** [comment] 2020-02-18 15:04
There is no such thing as incorrect delimiter @mohamedzayan19 delimiter can be any utf-8 character in S3 API.

So your server is misbehaving, we can't do anything to fix this on our end.

**Comment by mohamedzayan19** [comment] 2020-02-18 15:05
So my question is, can I edit the source code somehow to always send a "/" as a delimiter for  example?

**Comment by harshavardhana** [comment] 2020-02-18 15:07
No you shouldn't that is incorrect behavior @mohamedzayan19 server should be fixed.

**Comment by mohamedzayan19** [comment] 2020-02-18 15:08
Yes, I know it is incorrect behavior. However, for my specific use case, it would be a great solution.

**Comment by harshavardhana** [comment] 2020-02-18 15:08
A delimiter if set to / is non recursive, and if it's not set it means recursive. So cp and mirror operations would fail.

The issue is simply this is a server bug and should be fixed. If you wish to modify code to satisfy server would make this automatically S3 incompatible, then it is out of scope for us if you encounter any functionality issues.

**Comment by mohamedzayan19** [comment] 2020-02-18 15:15
Alright then, thanks alot

**Comment by mohamedzayan19** [comment] 2020-02-18 15:24
I am sorry, one more thing, can I change the empty delimiter to null?

**Comment by harshavardhana** [comment] 2020-02-18 15:31
No you cannot there is empty and non empty.

**Comment by harshavardhana** [comment] 2020-02-18 15:33
Let's close this, I don't think you can hack client here. 

Server should be fixed regardless.. this is the most basic of all behaviors in S3 API. So hacking here and there won't work conclusively.

**Closed by harshavardhana** 2020-02-18 15:33 UTC
Labels: community, not our bug
