### ISSUE TITLE
mc command has no "region" flag

### ISSUE THREAD

**Issue by bigxiong** [minio/mc#2435] opened 2018-04-17 09:44 UTC
I set the region="cn-north-1" while starting minio server. and I  use command "mc admin info minio --region "cn-north-1" ”  to get the admin info, but I got a an error message.

Incorrect Usage: flag provided but not defined: -region

mc admin info minio --region "cn-north-1"

## mc version
Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4

## System information
centos 6.5

**Comment by nitisht** [comment] 2018-04-17 12:27
closing as duplicate of https://github.com/minio/mc/issues/2411

**Closed by nitisht** 2018-04-17 12:27 UTC
