### ISSUE TITLE
Add STS support via new `mc sts` command

### ISSUE THREAD

**Issue by donatello** [minio/mc#2762] opened 2019-04-25 19:51 UTC
** Not using template **

Based on discussions with @abperiasamy we will be adding a new command to mc for the STS API. This will let users gain access to a Minio instance after being authenticated by an external identity provider (such as Kerberos).

**Comment by harshavardhana** [comment] 2019-11-10 01:57
Duplicate of #2891

**Closed by harshavardhana** 2019-11-10 01:57 UTC
Labels: priority: medium
