### ISSUE TITLE
`mc mb` command passed S3://  syntax results in bizarre behavior...

### ISSUE THREAD

**Issue by badscooter23** [minio/mc#2136] opened 2017-04-20 08:41 UTC
The issue was discovered when playing around with the the AWS CLI. The way it came up is that the AWS S3 CLI uses different syntax for URIs (path names to reference objects in S3). Specifically, in S3 you say

s3://bucket/object
for example 
aws s3 mb s3://foo1

The s3:// syntax is different than the minio labels (eg: s3/). 

If you use the defacto/legal AWS S3  syntax with `mc` you get some funky behavior… 

NOTE: the examples below are specfic to the `mc mb` command, but other commands also behave poorly when presented the `xyz://...` syntax (notably the `mc cp` command). 

## Expected behaviour

This is invalid syntax for `mc` and should result in a reasonable error... the actual result is no error and either `mc` does nothing or it creates a directory in the local file system... see below.

## Actual behaviour
Scotts-MacBook-Pro-2:testdir scott$ pwd
/Users/scott/testdir
Scotts-MacBook-Pro-2:testdir scott$ ls

Myminio has a two buckets `foo` and `test` with a few objects… 

Scotts-MacBook-Pro-2:testdir scott$ mc ls myminio --recursive
[2017-04-03 13:08:01 PDT] 2.0MiB foo/bar1
[2017-04-03 13:08:01 PDT] 1.1MiB foo/bar2
[2017-04-19 17:38:09 PDT] 6.0KiB test/.DS_Store
[2017-04-13 15:45:31 PDT]     8B test/bucket1/object1
[2017-04-13 15:45:45 PDT]     8B test/bucket1/object2
[2017-04-13 15:48:49 PDT]     8B test/bucket2/object3
[2017-04-13 15:49:00 PDT]     8B test/bucket2/object4
[2017-04-13 15:46:47 PDT]     8B test/object1
[2017-04-18 18:50:41 PDT]     8B test/object2
Scotts-MacBook-Pro-2:testdir scott$ mc ls myminio
[2017-04-03 06:08:49 PDT]     0B foo/
[2017-04-19 10:38:04 PDT]     0B test/

If we execute `mc mb myminio://foo1` … minio will say it succeeded but in reality it does nothing… 

Scotts-MacBook-Pro-2:testdir scott$ mc mb myminio://foo1
Bucket created successfully `myminio://foo1`.
Scotts-MacBook-Pro-2:testdir scott$ ls
Scotts-MacBook-Pro-2:testdir scott$ mc ls myminio
[2017-04-03 06:08:49 PDT]     0B foo/
[2017-04-19 10:38:04 PDT]     0B test/
Scotts-MacBook-Pro-2:testdir scott$ 
Let’s try the same thing with S3://

We have an S3 account which has a few buckets… 

Scotts-MacBook-Pro-2:testdir scott$ aws s3 ls
2017-04-19 09:02:21 scott-GoPro
2017-04-19 00:42:19 scott-main-bucket
2017-04-19 11:06:33 scott-mcclellan-test-bucket
2017-04-19 14:48:16 scott-test-bucket-us-west-2

Our S3 account is configured in `mc` and `mc ls s3` shows the same buckets… 

Scotts-MacBook-Pro-2:testdir scott$ mc ls s3
[2017-04-19 09:02:21 PDT]     0B scott-GoPro/
[2017-04-19 00:42:19 PDT]     0B scott-main-bucket/
[2017-04-19 11:06:32 PDT]     0B scott-mcclellan-test-bucket/
[2017-04-19 14:48:16 PDT]     0B scott-test-bucket-us-west-2/

If we try to use the S3://foo1 syntax to create a bucket in S3, `mc` again indicates that it succeeded (when it didn’t). 

Scotts-MacBook-Pro-2:testdir scott$ mc mb s3://foo1
Bucket created successfully `s3://foo1`.

But this time `mc` actually creates a file locally (in the local laptop file system) called `s3`:

Scotts-MacBook-Pro-2:testdir scott$ ls
S3:

And as you can see, `mc` did not create a bucket in S3 itself… 

Scotts-MacBook-Pro-2:testdir scott$ mc ls s3
[2017-04-19 09:02:21 PDT]     0B scott-GoPro/
[2017-04-19 00:42:19 PDT]     0B scott-main-bucket/
[2017-04-19 11:06:32 PDT]     0B scott-mcclellan-test-bucket/
[2017-04-19 14:48:16 PDT]     0B scott-test-bucket-us-west-2/

## Steps to reproduce the behaviour

see above 

## mc version
Scotts-MacBook-Pro-2:testdir scott$ mc version
Version: 2017-04-19T18:56:09Z
Release-tag: DEVELOPMENT.2017-04-19T18-56-09Z
Commit-id: 9a881562b93f5fb7af0968ab85282896caa81f9f

## System information

This is reproduced running `mc` from a Mac Laptop (but it probably does not matter what environment you try this in)

**Comment by badscooter23** [comment] 2017-04-20 20:25
I am looking at a fix for this already...

**Comment by deekoder** [comment] 2017-04-20 20:51
We have to definitely show an error message if this scheme is not supported in mc. For eg: 
```
mc mb xyz://fooo
mc: <ERROR> Invalid target `xyz://fooo`. Use `mc config host add mycloud xyz://fooo ...` to add an alias. Use the alias for S3 operations.
```

**Comment by deekoder** [comment] 2017-04-20 20:51
Lowering pri since root cause is known and the fix is clear.

**Comment by badscooter23** [comment] 2017-04-20 21:10
The cause is known, still debating the fix (lots of sidebar discussion with @harshavardhana) ... For this specific case there is an easy/straight forward fix, but for the bigger problem of inconsistency of error handling we need to make sure we have a good approach... 

My plan was to make a specific proposal for fixing this and the bigger issue...

**Comment by ebozduman** [comment] 2017-10-03 23:39
@badscooter23 :
This is about detecting if a provided parameter is invalid for `mc mb` command. However, `mc mb` command also fully supports native file system command `mkdir -p`. So, assuming an input parameter is wrong just because it doesn't fit the `mc` command's expectations, could open up new potentials for bugs. Maybe the user wants to create an object/directory locally and the format we consider wrong is actually what s/he wants.
After discussing this further with @harshavardhana, while we realize the need for time for the user to get used to `mc` command's behavior, we've decided that trying to fix this issue would be superfluous.
As a result, closing this issue as `wontfix/invalid` would be the best way to go at the moment.
Please let us know if you disagree.

**Closed by ebozduman** 2017-10-03 23:39 UTC
Labels: priority: medium
