### ISSUE TITLE
mirror: mc mirror fails to create destination prefix it doesn't exist.

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#1858] opened 2016-10-18 10:17 UTC
mc mirror fails:

```
root@minio-client3:~/krishna# mc mirror mc minio6/kris/mc-backup
mc: <ERROR> Unable to stat target ‘minio6/kris/mc-backup’. Object key is missing, object key cannot be empty
root@minio-client3:~/krishna# 
```

**Comment by radutopala** [comment] 2016-10-30 10:30
@krishnasrinivas first create a small file:
```
echo "create" | mc pipe minio6/kris/mc-backup/.create
```

**Comment by harshavardhana** [comment] 2016-10-30 16:22
> mc mirror fails:
> 
> root@minio-client3:~/krishna# mc mirror mc minio6/kris/mc-backup
> mc: <ERROR> Unable to stat target ‘minio6/kris/mc-backup’. Object key is missing, object key cannot be empty
> root@minio-client3:~/krishna#

Is `mc` a file or directory? @krishnasrinivas

**Comment by harshavardhana** [comment] 2016-10-30 16:22
Can you also paste "--debug" output.

**Comment by krishnasrinivas** [comment] 2016-10-31 19:53
@harshavardhana i have assigned it to myself, will fix it

**Comment by harshavardhana** [comment] 2016-10-31 19:57
> @harshavardhana i have assigned it to myself, will fix it

Is it still an issue? under what conditions does this occur.

**Comment by krishnasrinivas** [comment] 2016-10-31 20:00
`asd` is a local dir with few files in it.
happens if prefix `asd/` does not exist on minio.

```
krishna@escape:~$ mc mirror asd myminio/testbucket/asd
mc: <ERROR> Unable to stat target ‘myminio/testbucket/asd’. Object key is missing, object key cannot be empty
krishna@escape:~$ mc cp /etc/passwd myminio/testbucket/asd/passwd
/etc/passwd:    2.20 KB / 2.20 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 384.50 KB/s 0skrishna@escape:~$ mc mirror asd myminio/testbucket/asd
...ormat.json:  3.02 KB / 3.02 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 147.48 KB/s 0skrishna@escape:~$ 

```

**Comment by harshavardhana** [comment] 2016-10-31 20:04
Ah that way @krishnasrinivas - it is supposed to work.

**Comment by vadmeste** [comment] 2016-10-31 20:08
I guess this happens because the code tries to compare the content of source and target directory before deciding what files to synchronize

**Comment by harshavardhana** [comment] 2016-10-31 20:38
> I guess this happens because the code tries to compare the content of source and target directory before deciding what files to synchronize

Its an issue with url2Stat() there is no need to stat the destination here.

**Comment by harshavardhana** [comment] 2016-11-24 09:44
@krishnasrinivas - do you have a fix for this?

**Comment by supernova32** [comment] 2016-11-25 22:24
I'm getting a very similar error when using `mc watch`. It is most likely caused by the same bug as the error pointed out by @krishnasrinivas. Here is my `--debug` output.

```
mc: <DEBUG> GET /public/?location= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.1 mc/2016-10-07T01:56:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161125/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161125T222035Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 25 Nov 2016 22:20:35 GMT
Server: Minio/RELEASE.2016-10-24T21-23-47Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: TBJT9H7D1MWIEY0K

mc: <DEBUG> Response Time:  4.062683ms

mc: <DEBUG> GET /public/?events=s3%3AObjectCreated%3A%2A&events=s3%3AObjectRemoved%3A%2A&prefix=&suffix= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.1 mc/2016-10-07T01:56:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161125/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161125T222035Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 25 Nov 2016 22:20:35 GMT
Server: Minio/RELEASE.2016-10-24T21-23-47Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: X0Q4Q9ZQD3GGITXS

mc: <DEBUG> Response Time:  6.295824ms

mc: <ERROR> Cannot watch on events. invalid character '<' looking for beginning of value
 (0) client-s3.go:400 cmd.(*s3Client).Watch.func2(..)
 Release-Tag:RELEASE.2016-10-07T01-56-22Z | Commit:75d55783c01c | Host:Patricios-MBP.lan | OS:darwin | Arch:amd64 | Lang:go1.7.3 | Mem:1.5MB/5.9MB | Heap:1.5MB/2.5MB
```


As reference, I tried an older version of `mc`, "2016-08-21T03:02:49Z", and it does work there.

```
mc: <DEBUG> GET /public/?location= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.1 mc/2016-08-21T03:02:49Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161125/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161125T222251Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 25 Nov 2016 22:22:51 GMT
Server: Minio/RELEASE.2016-10-24T21-23-47Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: IKLYXAS6SKDY19A8

mc: <DEBUG> Response Time:  3.277936ms

mc: <DEBUG> GET /public/?notification= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.1 mc/2016-08-21T03:02:49Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161125/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161125T222251Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/plain; charset=utf-8
Date: Fri, 25 Nov 2016 22:22:51 GMT
Server: Minio/RELEASE.2016-10-24T21-23-47Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: L3RMKDPOIGE8OFE3

mc: <DEBUG> Response Time:  1.296989ms

mc: <DEBUG> PUT /public/?notification= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.1 mc/2016-08-21T03:02:49Z
Content-Length: 218
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161125/us-east-1/s3/aws4_request, SignedHeaders=content-md5;expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Md5: H47mU6BXezNHrUWK02mD0g==
Expect: 100-continue
X-Amz-Content-Sha256: 1ecb390d8f3663e748b41da09354f705bacd2e690ae7825bfe2d44b5431371b5
X-Amz-Date: 20161125T222251Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Fri, 25 Nov 2016 22:22:51 GMT
Server: Minio/RELEASE.2016-10-24T21-23-47Z (darwin; amd64)
Vary: Origin
X-Amz-Request-Id: 3IZ63PIR653L7KFA

mc: <DEBUG> Response Time:  1.467738ms
```

**Comment by vadmeste** [comment] 2016-12-05 10:44
@supernova32, sorry for the delay, I was not able to reproduce your bug, if you ever see it again, can you open a new issue with more information ?

@krishnasrinivas, I am taking this if you did not start to work on it.

**Comment by harshavardhana** [comment] 2016-12-05 17:44
> mc: <ERROR> Cannot watch on events. invalid character '<' looking for beginning of value
>  (0) client-s3.go:400 cmd.(*s3Client).Watch.func2(..)
>  Release-Tag:RELEASE.2016-10-07T01-56-22Z | Commit:75d55783c01c | Host:Patricios-MBP.lan | OS:darwin | Arch:amd64 | Lang:go1.7.3 | Mem:1.5MB/5.9MB | Heap:1.5MB/2.5MB

This is because the `mc watch` is old version, server changed the API as well - we will make a new release.

**Comment by harshavardhana** [comment] 2016-12-06 09:43
> This is because the mc is old version, server changed the API as well - we will make a new release.

A new release is done so should fix @supernova32 's issue.

**Comment by supernova32** [comment] 2016-12-06 17:06
Thanks @harshavardhana! 👍

**Comment by GarimaKapoor** [comment] 2016-12-11 22:26
@harshavardhana can we close this issues, if this is not reproducible anymore.

**Comment by harshavardhana** [comment] 2017-01-06 09:30
This is fixed in master.

**Closed by harshavardhana** 2017-01-06 09:30 UTC
Labels: bug
