### ISSUE TITLE
mc does not preserve anonymous policy with --preserve 

### ISSUE THREAD

**Issue by fcomte** [minio/mc#3543] opened 2020-12-19 10:21 UTC
## Expected behavior
policy should be copy from source to destination when doing 
`mc mirror --preserve lab/bucket kub/bucket`

## Actual behavior
```
mc policy list lab/bucket
bucket/* => none

root@~[10:15:56]# mc policy --insecure list kub/bucket
root@~[10:16:04]#
```
## Steps to reproduce the behavior

Just create an anonymous policy on a source bucket and try to mirror this bucket to a new location.

## mc --version
`mc version RELEASE.2020-10-03T02-54-56Z`

**Comment by harshavardhana** [comment] 2020-12-19 17:35
This is on purpose to avoid security complications that may arise on the mirrored bucket, we are deliberately by design, not mirroring anonymous bucket policies.

**Comment by fcomte** [comment] 2020-12-19 17:46
so when we need to migrate from one minio cluster to another, what is the best way to not lose this kind of policy ?

**Comment by fcomte** [comment] 2020-12-19 17:47
it would be very convenient to have such a mirroring option I think.

**Comment by harshavardhana** [comment] 2020-12-20 00:05
> so when we need to migrate from one minio cluster to another, what is the best way to not lose this kind of policy ?

Generally yes but we would not want to automate this, as it may unexpectedly expose your content even with good intentions. I would suggest you manually do it once the migration is done by manually selecting and re-applying the necessary anonymous policies.

**Comment by kannappanr** [comment] 2020-12-21 16:16
based on the above response closing the issue. Please feel free to reach out to us if you have further questions.

**Closed by kannappanr** 2020-12-21 16:16 UTC
Labels: community, triage
