### ISSUE TITLE
Add support for glob patterns and/or prefixes to "mc"

### ISSUE THREAD

**Issue by tmbdev** [minio/mc#2117] opened 2017-04-09 04:18 UTC
## Expected behaviour

I would like 

`mc rm server/bucket/prefix-*`

to remove all files starting with `prefix-` from the bucket.

Other glob patterns should also work.

Alternatively, a simpler form might be to just add a "prefix" option, as in:

`mc rm --prefix server/bucket/prefix-`

## Actual behaviour

mc: <ERROR> Failed to remove ‘server/bucket/prefix-*’. Object key is missing, object key cannot be empty

## Steps to reproduce the behaviour

run `mc rm server/bucket/prefix-*`

## mc version

Version: DEVELOPMENT.GOGET
Release-tag: DEVELOPMENT.GOGET
Commit-id: DEVELOPMENT.GOGET

## System information

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by badscooter23** [comment] 2017-04-10 19:26
Per discussions with AB there are multiple topics that are related to ...

- expected behavior for and `mc` command where the user specified a path name and --recursive
- the desire to accept wildcards and/or regular expressions on multiple commands

I would like to tie this together into a more comprehensive proposal... 
Can you assign this to me (for now) and I will do a write up on this? 

Thx

**Comment by harshavardhana** [comment] 2017-07-13 09:24
This is not blocked anymore currently being addressed in #2201

**Comment by ebozduman** [comment] 2017-09-02 02:18
Removed `Blocked` label per @harshavardhana 's comment.

**Comment by ebozduman** [comment] 2017-09-02 02:50
Closing it since it is a duplicate of https://github.com/minio/mc/pull/2201

**Closed by ebozduman** 2017-09-02 02:50 UTC
Labels: community, priority: medium
