### ISSUE TITLE
mc cp command with "-a" (or) "--preserve" doesnt preserve the timestamp from source path

### ISSUE THREAD

**Issue by udhayd** [minio/mc#3968] opened 2022-02-09 05:54 UTC
## Expected behavior
To Preserve the date & timestamp of files during the object copy from one directory path to another directory path.

## Actual behavior
To Get the files preserved with actual date & timestamp of object during copy.

## Steps to reproduce the behavior
Please find the below mc command output from find and ls output 

We made a attempt to copy files from "myminio/test-landing/unwanted" older-than 2days to "myminio/test-landing/temp2" path. Though files got copied , it doesnt have the same timestamp .

Copied Files in "myminio/test-landing/temp2" path doesn't have the same timestamp as "myminio/test-landing/unwanted".

# mc find  myminio/test-landing/unwanted --older-than 2d --exec "mc ls {}"
**[2022-02-04 07:10:27 UTC]     0B STANDARD file.tar.GZ
[2022-02-03 14:30:31 UTC]    31B STANDARD file1.gz
[2022-02-03 14:30:31 UTC]    31B STANDARD file2.gz
[2022-02-03 14:30:31 UTC]    31B STANDARD file3.gz
[2022-02-03 14:30:31 UTC]    31B STANDARD file4.gz
[2022-02-03 14:30:31 UTC]    31B STANDARD file5.gz
[2022-02-04 07:10:28 UTC]    31B STANDARD file6.gz
[2022-02-04 07:10:28 UTC]    31B STANDARD file7.gz
[2022-02-04 07:10:28 UTC]    31B STANDARD file8.gz
[2022-02-04 07:10:28 UTC]    31B STANDARD file9.gz
[2022-02-03 14:30:31 UTC]   850B STANDARD test.tar.gz
[2022-02-03 14:20:30 UTC]   873B STANDARD test.tar.gz.gz
[2022-02-03 14:20:30 UTC]   873B STANDARD test.tar.gz.gz
[2022-02-04 07:10:28 UTC]   174B STANDARD test1.tar.gz
[2022-02-03 14:20:30 UTC]   492B STANDARD test1.tar.gz.gz
[2022-02-03 14:20:30 UTC]   492B STANDARD test1.tar.gz.gz
[2022-02-03 14:30:31 UTC]   703B STANDARD test2.tar.gz
[2022-02-03 14:20:30 UTC]   726B STANDARD test2.tar.gz.gz
[2022-02-03 14:20:30 UTC]   726B STANDARD test2.tar.gz.gz**
#

# mc ls "myminio/test-landing/temp2/"
[2022-02-09 05:36:32 UTC]     0B STANDARD file.tar.GZ
[2022-02-09 05:36:33 UTC]    31B STANDARD file1.gz
[2022-02-09 05:36:34 UTC]    31B STANDARD file2.gz
[2022-02-09 05:36:34 UTC]    31B STANDARD file3.gz
[2022-02-09 05:36:35 UTC]    31B STANDARD file4.gz
[2022-02-09 05:36:35 UTC]    31B STANDARD file5.gz
[2022-02-09 05:36:36 UTC]    31B STANDARD file6.gz
[2022-02-09 05:36:37 UTC]    31B STANDARD file7.gz
[2022-02-09 05:36:38 UTC]    31B STANDARD file8.gz
[2022-02-09 05:36:38 UTC]    31B STANDARD file9.gz
[2022-02-09 05:36:39 UTC]   850B STANDARD test.tar.gz
[2022-02-09 05:36:39 UTC]   873B STANDARD test.tar.gz.gz
[2022-02-09 05:36:40 UTC]   174B STANDARD test1.tar.gz
[2022-02-09 05:36:41 UTC]   492B STANDARD test1.tar.gz.gz
[2022-02-09 05:36:41 UTC]   703B STANDARD test2.tar.gz
[2022-02-09 05:36:42 UTC]   726B STANDARD test2.tar.gz.gz
#

## mc --version
mc version RELEASE.2022-02-02T02-03-24Z

## System information
minio Server version - RELEASE.2021-12-20T22-07-16Z

**Comment by harshavardhana** [comment] 2022-02-09 06:39
Closing as duplicate of #3967

**Closed by harshavardhana** 2022-02-09 06:39 UTC
Labels: community, triage
