### ISSUE TITLE
Gigantic crash while doing mirror between 2 buckets

### ISSUE THREAD

**Issue by HyperDevil** [minio/mc#2485] opened 2018-07-17 19:24 UTC
## Expected behaviour
Mirror files between 2 buckets (one is aws and second in wasabi)

## Actual behaviour
Works fine for about 4 GB, then mc mirror crashes in a gigantic long error message

## Steps to reproduce the behaviour
copy between the 2 buckets again, does not happen on small (125GB bucket).
This bucket is about 70GB but around 500k files.

## mc version
Version: 2018-07-13T00:53:22Z
Release-tag: RELEASE.2018-07-13T00-53-22Z
Commit-id: 70dcf20d747d305f73a117b4787acf46e6809d99

## System information
Amazon EC2 instance Debian 9, all updated
4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

## Error Message
` goroutine 255707 [sleep]: 
time.Sleep(0xe23ef0e)
        /opt/go/src/runtime/time.go:102 +0x166
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer.func2(0xc476171320, 0xa, 0xc4761712c0, 0xc4761dade0)
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:82 +0x84
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:72 +0x161

goroutine 255600 [IO wait]:
internal/poll.runtime_pollWait(0x7f84ecdd8968, 0x72, 0xc44e784760)
        /opt/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc475dd9498, 0x72, 0xffffffffffffff00, 0x9821e0, 0xb882c8)
        /opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc475dd9498, 0xc4762aa000, 0x8000, 0x8000)
        /opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc475dd9480, 0xc4762aa000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc475dd9480, 0xc4762aa000, 0x8000, 0x8000, 0x9d23, 0xc47629b3f0, 0x5)
        /opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc47553bb88, 0xc4762aa000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc475e98960, 0x7f84ed290250, 0xc47553bb88, 0x5, 0xc47553bb88, 0x10f)
        /opt/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc475ddd880, 0x940817, 0xc475ddd9a0, 0x454210)
        /opt/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc475ddd880, 0xc475ef2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/go/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc475dbe900, 0xc475ef2000, 0x1000, 0x1000, 0xc44e784b98, 0x403355, 0xc475eb64e0)
        /opt/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc475ede360)
        /opt/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc475ede360, 0x1, 0x0, 0x0, 0x0, 0xc473429260, 0x0)
        /opt/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc475dbe900)
        /opt/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /opt/go/src/net/http/transport.go:1237 +0x95a

goroutine 255724 [IO wait]:
internal/poll.runtime_pollWait(0x7f84ecdd8bd8, 0x72, 0xc420130918)
        /opt/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc475dd9b98, 0x72, 0xffffffffffffff00, 0x9821e0, 0xb882c8)
        /opt/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc475dd9b98, 0xc476246400, 0x400, 0x400)
        /opt/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc475dd9b80, 0xc476246400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc475dd9b80, 0xc476246400, 0x400, 0x400, 0xc476246400, 0x0, 0x400)
        /opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4761043e8, 0xc476246400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc476244870, 0x7f84ed290250, 0xc4761043e8, 0x5, 0xc4761043e8, 0xc475dd9b98)
        /opt/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc47618f500, 0x940816, 0xc420130c80, 0xa2)
        /opt/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).readHandshake(0xc47618f500, 0xc47617ba16, 0xc47617bad0, 0xa2, 0xa2)
        /opt/go/src/crypto/tls/conn.go:965 +0x8d
crypto/tls.(*clientHandshakeState).handshake(0xc420130e70, 0xc476143680, 0x0)
        /opt/go/src/crypto/tls/handshake_client.go:191 +0xaa
crypto/tls.(*Conn).clientHandshake(0xc47618f500, 0x940870, 0xc47618f620)
        /opt/go/src/crypto/tls/handshake_client.go:168 +0x38c
crypto/tls.(*Conn).Handshake(0xc47618f500, 0x0, 0x0)
        /opt/go/src/crypto/tls/conn.go:1329 +0x185
net/http.(*persistConn).addTLS.func2(0x0, 0xc47618f500, 0xc4761e0b40, 0xc4761fdda0)
        /opt/go/src/net/http/transport.go:1068 +0x42
created by net/http.(*persistConn).addTLS
        /opt/go/src/net/http/transport.go:1064 +0x19f

goroutine 255611 [sleep]: 
time.Sleep(0x150059d2)
        /opt/go/src/runtime/time.go:102 +0x166
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer.func2(0xc475eb6ae0, 0xa, 0xc475eb6a80, 0xc475efc3f0)
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:82 +0x84
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:72 +0x161

goroutine 255931 [sleep]: 
time.Sleep(0x289e61ff)
        /opt/go/src/runtime/time.go:102 +0x166
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer.func2(0xc47669ec60, 0xa, 0xc47669ec00, 0xc4766a94a0)
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:82 +0x84
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:72 +0x161

goroutine 255576 [select]:
net/http.(*persistConn).writeLoop(0xc475d2d560)
        /opt/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /opt/go/src/net/http/transport.go:1238 +0x97f
`

**Comment by HyperDevil** [comment] 2018-07-17 20:21
After trying different settings, HTTP, HTTPS and different API versions. 
Although i get about 1GB extra mirrored with S3V2 it still crashes with the same error message.
/q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:72 +0x161

**Comment by vadmeste** [comment] 2018-07-17 20:43
@HyperDevil thanks for reporting this. I believe that the stack trace that you pasted is not complete. It would be a big help for us if you paste the whole stacktrace (golang usually prints the reason of the crash: segfault, out of memory, index out of bounds, ..)

**Comment by HyperDevil** [comment] 2018-07-17 20:49
I am running the copy again now on another server with a lott more memory.
The logfile is going to be quite big, i will paste it on pastebin as soon as it crashes again.

**Comment by deekoder** [comment] 2018-07-17 22:45
you can also come join us in slack and we can have 1-1 conversation with you and you can attach the log file there.

**Comment by deekoder** [comment] 2018-07-20 16:53
Ping @HyperDevil  are you able to share the full stacktrace.

**Comment by kannappanr** [comment] 2018-07-23 21:17
@HyperDevil I did try reproducing this issue on a bucket with files of size `100KB` each and bucket size of `20+GB`. I was mirroring the bucket and I had to stop after `7+GB` of data transfer, but was unable to reproduce the issue. I did this locally. I can try to `mirror` between a `local` minio server and an` external s3` server if possible.

**Comment by HyperDevil** [comment] 2018-07-24 08:48
i did the mirroring between AWS and Wasabi.

**Comment by deekoder** [comment] 2018-07-30 23:45
@HyperDevil we need your help to understand repro. But are unable to. So we will close this issue and we can reopen it if you will be able to help us with the repro to do root cause analysis.

**Closed by deekoder** 2018-07-30 23:45 UTC
Labels: blocked, community, priority: medium, triage, working as intended
