### ISSUE TITLE
 Unable to display heal status. No such heal process is running on the server

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3256] opened 2020-06-16 14:03 UTC
Trying to run heal process on an otherwise healthy cluster with 7 hosts 2 drives each host, mc exist after a few minutes with the below error

# mc admin heal -r --scan deep dot9
 _  lxc.snapshots/xxxxxxx
    0/3,712 objects; 2 GiB in 6m45s
    ________________________________________
    _ Green  _ 3,746 _ 100.0% ____________ _
    _ Yellow _     0 _   0.0%              _
    _ Red    _     0 _   0.0%              _
    _ Grey   _     0 _   0.0%              _
    ________________________________________
mc: <ERROR> Unable to display heal status. No such heal process is running on the server. 

What does it mean ?

mc --version
mc version RELEASE.2020-04-19T19-17-53Z

**Comment by kannappanr** [comment] 2020-06-17 21:03
@i0x71 I couldn't reproduce this issue with the latest version of minio. Can you please test it with the latest version of MinIO?

**Comment by harshavardhana** [comment] 2020-06-18 05:36
> @i0x71 I couldn't reproduce this issue with the latest version of minio. Can you please test it with the latest version of MinIO?

Most probably @i0x71 is trying to initiate this `mc admin heal` behind a proxy. Is there a good reason are you running this manually? @i0x71

**Comment by vadmeste** [comment] 2020-07-07 15:04
This issue should be fixed by https://github.com/minio/minio/pull/9939, closing.

**Closed by vadmeste** 2020-07-07 15:04 UTC
Labels: community, triage
