### ISSUE TITLE
Not able to add multiple notifications for same event but with different prefix

### ISSUE THREAD

**Issue by shatgupt** [minio/mc#2386] opened 2018-02-08 10:33 UTC
## Expected behaviour
S3 allows adding multiple event notification for same event (say PUT) on same bucket with different prefix.

## Actual behaviour
But with minio and mc, I am getting following error:
```shell
www-data@localhost:~$ mc events add myminio/test arn:minio:sqs::1:webhook --events put --prefix abc
Successfully added arn:minio:sqs::1:webhook
www-data@localhost:~$ mc events add myminio/test arn:minio:sqs::1:webhook --events put --prefix xyz
mc: <ERROR> Cannot enable notification on the specified bucket. Configurations overlap. Configurations on the same bucket cannot share a common event type.
```

## Steps to reproduce the behaviour
```
mc events add myminio/test arn:minio:sqs::1:webhook --events put --prefix abc
mc events add myminio/test arn:minio:sqs::1:webhook --events put --prefix xyz
```

## mc version
```
Version: 2018-01-18T21:18:56Z
Release-tag: RELEASE.2018-01-18T21-18-56Z
Commit-id: d9663e5d96d5f32725867167de2a0403704ae537
```
## System information
Ubuntu 14.04

I am thinking it is related to https://github.com/minio/mc/issues/2324 which is due to Deepequal not working properly, being fixed in https://github.com/minio/minio-go/pull/917

**Comment by nitisht** [comment] 2018-02-08 11:05
@shatgupt I think the root cause is same as https://github.com/minio/mc/issues/2324 . The issue is being addressed here https://github.com/minio/minio-go/pull/917

**Comment by harshavardhana** [comment] 2018-02-10 02:05
Moving this to @balamurugana since has fixed it in https://github.com/minio/minio/pull/5294 full notification refactor

**Comment by balamurugana** [comment] 2018-03-07 07:31
@shatgupt PR https://github.com/minio/minio/pull/5294 fixes this issue.  Please try and let me know.

**Comment by harshavardhana** [comment] 2018-03-16 04:42
Above referenced PR is merged @shatgupt you can pull the latest master from `docker pull minio/minio:edge` and let us know if this issue is fixed ?

**Comment by deekoder** [comment] 2018-03-21 22:58
Closing as fixed, @shatgupt . Please reactivate if this issue still occurs.

**Closed by deekoder** 2018-03-21 22:58 UTC
Labels: fixed, priority: medium
