### ISSUE TITLE
mc: conflicts with mc

### ISSUE THREAD

**Issue by silvernode** [minio/mc#2260] opened 2017-09-25 06:10 UTC
## Expected behaviour
Midnight Commander opens
## Actual behaviour
minio opens instead
## Steps to reproduce the behaviour
1. install midnight commander
2. install minio
3. run mc
4. midnight commander doesn't open
## mc version
N/A

## System information
N/A

**Comment by harshavardhana** [comment] 2017-09-25 06:57
https://github.com/minio/mc/blob/master/CONFLICT.md

**Comment by silvernode** [comment] 2017-09-25 13:21
How about minc? I kind of like it better actually because it makes me think of Minks.

**Comment by harshavardhana** [comment] 2017-09-25 15:35
It doesn't matter what you name the binary locally for your purposes.

**Comment by ebozduman** [comment] 2017-09-25 18:49
@silvernode :
We would like to close it as `working as intended` as this is a small collision and you can always rename Minio Client (mc) the way you'd like.
Please let us know if you are OK with it. Thanks...

**Comment by silvernode** [comment] 2017-09-25 23:37
Well I would suggest another name just for the sake of clarity, although it's your project and you can do what you wish. The fact that Midnight Commander has existed since the beginning of Linux makes me feel like it should get to claim "mc" as it's command name. Maybe only old time Linux users will understand where I am coming from. Midnight Commander is such a timeless application and I don't think anyone should have to bother renaming minio. This is exactly why namespaces and trademarks exist. Just my 2 cents, you can close this issue any time you wish.

**Comment by balamurugana** [comment] 2017-09-26 01:58
Minio Client as `mc` is project which creates a single statically compiled executable binary which can be placed anywhere (by any name)  in the system for user convenience.

When distributing mc's executable, package maintainer could choose convenient name which works for the system.  We encourage this.  Package maintainers are already doing it e.g. Ubuntu snap is called as minio-client.

Hope this helps.

**Closed** 2017-09-26 03:12 UTC
Labels: priority: medium, triage, working as intended

**Comment by guettli** [comment] 2019-03-19 14:03
Wow, this is already the third ticket about the same ticket. Let's fight unemployment and create work by creating confusion. Dear minio creators: please think about this again. If you want `mc` then you can create an alias for your. I think the current name conflict can only be solved by minio devs by choosing a different name.

**Comment by harshavardhana** [comment] 2019-03-19 15:56
@guettli the ship has sailed on that, mc will remain as mc.
