### ISSUE TITLE
  mc rm  command is not working  with latest docker image minio/mc:RELEASE.2019-04-10T22-11-28Z

### ISSUE THREAD

**Issue by sanverm2** [minio/mc#2749] opened 2019-04-17 05:41 UTC
## Expected behavior

The command  `mc rm  test/sanjay` must delete the bucket.

## Actual behavior

```
/ # mc rm  test/sanjay
mc: <ERROR> Failed to remove `test/sanjay`. Target `test/sanjay` not found.
/ # 
```

## Steps to reproduce the behavior

Launch mc pod on Kubernetes environment 

```
apiVersion: v1
kind: Pod
metadata:
  name: minioclient
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: minioclient
spec:
  containers:
  - name: minio
    #image: minio/mc:RELEASE.2018-06-09T02-18-09Z
    image: minio/mc:RELEASE.2019-04-10T22-11-28Z
    imagePullPolicy: IfNotPresent
    command: ["/test/test-minio.sh"]
    volumeMounts:
      - name: test-minio
        mountPath: "/test"
  volumes:
    - name: test-minio
      configMap:
        name: test-minio
        defaultMode: 0744
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-minio
data:
  test-minio.sh: |
    #!/bin/sh
    mc config host add myminio http://minio-ibm-minio-objectstore:9000 admin admin1234 S3v4
    #mc mb test/test
    #mc ls test/test
    sleep 3600
```

Logon to mc po and connect to Minio server running with   
minio/minio: RELEASE.2019-04-09T01-22-30Z image 

```
/ # mc config host add test http://rwpbjld-ibm-minio-objectstore:9000 admin admin1234 
Added `test` successfully.
/ # mc mb test/sanjay
Bucket created successfully `test/sanjay`.
/ # mc ls test/sanjay
/ # mc rm  test/sanjay
mc: <ERROR> Failed to remove `test/sanjay`. Target `test/sanjay` not found.
/ # 
```

## mc version
```
root@sanjay33-ubt-master:~/test-dir/minio_test# kubectl exec -it minioclient sh 
/ # mc version 
Version: 2019-04-10T22:11:28Z
Release-tag: RELEASE.2019-04-10T22-11-28Z
Commit-id: ea469140d50b0240501963666e1de19c6d37f812
/ # 
```

## System information

Kubernetes cluster 

```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4+icp-ee", GitCommit:"5da3fdf4758c9bbb168d480cbda91b754e3b9b3e", GitTreeState:"clean", BuildDate:"2019-03-11T00:42:41Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4+icp-ee", GitCommit:"5da3fdf4758c9bbb168d480cbda91b754e3b9b3e", GitTreeState:"clean", BuildDate:"2019-03-11T00:42:41Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nitisht** [comment] 2019-04-17 05:47
This is know and should be fixed with https://github.com/minio/mc/pull/2748

Can you confirm using the `minio/mc:edge` image @sanverm2

**Comment by nitisht** [comment] 2019-04-17 05:48
Duplicate of #2746

**Comment by kannappanr** [comment] 2019-04-17 05:56
@sanverm2 please use `mc rb test/sanjay` to delete an empty bucket and `mc rb --force  test/sanjay` to delete bucket with all the objects inside it.

**Comment by kannappanr** [comment] 2019-04-17 05:57
`mc rm` does not delete buckets anymore. This has been the case for the last few releases

**Comment by kannappanr** [comment] 2019-04-17 05:58
Closing this issue now. Please try `minio/mc:edge` as suggested by @nitisht . Please feel free to get back to us if you have further questions

**Closed by kannappanr** 2019-04-17 05:58 UTC
Labels: duplicate
