### ISSUE TITLE
mc: <ERROR> Unable to initialize new alias from the provided credentials...

### ISSUE THREAD

**Issue by tomasyhy** [minio/mc#3599] opened 2021-02-08 08:28 UTC
Hello!

When i try to run image I get following error:

`mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio.xoz.one:9000/probe-bucket-sign-zr2ldif4zcrv/?location=": dial tcp 172.23.0.3:9000: connect: connection refused.`

## mc --version
minio/mc:latest

## System information
Ubuntu 20.04.1 LTS

**Comment by harshavardhana** [comment] 2021-02-08 08:41
> When i try to run image I get following error:
> 
> `mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio.xoz.one:9000/probe-bucket-sign-zr2ldif4zcrv/?location=": dial tcp 172.23.0.3:9000: connect: connection refused.`

Server is not reachable @tomasyhy

**Comment by tomasyhy** [comment] 2021-02-08 08:47
Thanks, any tips how solve this? Where to find cause? Sorry, I don't have much experience with docker

**Comment by lhridley** [comment] 2021-03-08 14:56
This issue just started for me as well.  I have been using MinIO for local development for quite some time, and this was working last week, is not working now.

**minio / mc --versions**
minio/minio:RELEASE.2021-01-05T05-22038Z
minio/mc:RELEASE.2021-01-05T05-03-58Z

**relevant docker-compose service configuration:**
# Development compose file.
version: '3.7'
services:
....  
  minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    ports:
      - 8000:9000
    volumes:
      - flysystemdata:/data
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    command: server /data

  createbuckets:
    image: minio/mc:RELEASE.2021-01-05T05-03-58Z
    depends_on:
      - minio
        ## To create Bucket with no public policy, add the following lines
        ## after configuring the host, but before "exit 0;"
        ## change "bucketnpa" to your desired bucket name
        ##
        ## /usr/bin/mc mb minio/bucketnpa;
        ## /usr/bin/mc policy none minio/bucketnpa;
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - BUCKET_NAME=localbucket
      - ENDPOINT=http://minio:9000
    entrypoint: >
        /bin/sh -c "
        /usr/bin/mc config host add minio http://minio:9000 minio-access-key minio-secret-key;
        /usr/bin/mc mb minio/localbucket;
        /usr/bin/mc policy set public minio/localbucket;
        exit 0;
        "
volumes:
  flysystemdata: {}

System information:
Ubuntu 20.04 LTS
Docker: version 19.03.8, build afacb8b7f0 (installed from Ubuntu package manager)
Docker Compose: version 1.25.0, build unknown (installed from Ubuntu package manager)

**Comment by MartinP7r** [comment] 2021-03-11 05:16
@lhridley it might be a different issue, but you could try changing your entrypoint logic to the one suggested in this post comment:
https://github.com/minio/mc/issues/3421#issuecomment-699597252

**Comment by ebozduman** [comment] 2021-04-12 10:03
@tomasyhy, @lhridley,
Do you still see the problem after changing the entry point make sure the minio server has good enough time to come up?

This is a very basic communication issue. You cannot reach the server because either it is not up yet, or the server went down.

Please let us know if you still see the issue even after you wait for some time so that the server can come up to provide full service.

**Comment by ebozduman** [comment] 2021-04-17 00:17
@tomasyhy, @lhridley,

Since we did not hear from you guys, we'll assume changing the entry point and giving some extra time to MinIO server to come up works for you.

So, closing the issue.

Please reopen/create the/a-new issue and provide clear reproduction steps as much as possible.

**Closed by ebozduman** 2021-04-17 00:17 UTC
Labels: community, working as intended

**Comment by capriciousduck** [comment] 2021-07-11 17:21
Any workaround? I am getting the same error.

**Comment by ebozduman** [comment] 2021-07-14 00:45
@capriciousduck,

Did you try the recommended entry point change in docker-compose.yml file?

Please check it out (explained above) and if it doesn't work for you, open a new issue since the issue addressed here is already resolved.

**Comment by Mageswaran1989** [comment] 2021-12-10 09:26
I am getting the same error when I try to run on minikube with 4 nodes:

```
$ minikube start --nodes 4 

$ kubectl create namespace mozhi

$ kubectl minio tenant create mozhitenant \
  --servers                 4                   \
  --volumes                 16                   \
  --capacity                16Gi                 \
  --namespace               mozhi 
```

```
$ kubectl -n mozhi get all


NAME                     READY   STATUS    RESTARTS   AGE
pod/mozhitenant-ss-0-0   1/1     Running   0          8m46s
pod/mozhitenant-ss-0-1   1/1     Running   0          8m45s
pod/mozhitenant-ss-0-2   1/1     Running   0          8m45s
pod/mozhitenant-ss-0-3   1/1     Running   0          8m45s

NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/minio                 ClusterIP   10.100.183.34    <none>        443/TCP    8m46s
service/mozhitenant-console   ClusterIP   10.109.150.210   <none>        9443/TCP   8m46s
service/mozhitenant-hl        ClusterIP   None             <none>        9000/TCP   8m46s

NAME                                READY   AGE
statefulset.apps/mozhitenant-ss-0   4/4     8m46s
```

**Comment by ebozduman** [comment] 2021-12-10 10:54
@Mageswaran1989,
The problem reported in this issue has been already addressed.  
Please file a separate issue.

**Comment by baptisteArno** [comment] 2022-03-03 15:12
Adding a `sleep` command to the entrypoint did the trick for me:

```yml
version: '3.6'
services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc policy set public minio/typebot;
      exit 0;
      "
volumes:
  s3_data:

```

**Comment by cniackz** [comment] 2022-06-16 23:59
Adding a `sleep` command did the trick for me as well...
We need to give MinIO Server time to be ready for `mc` commands to be launched.
And time for Server to be reachable as well.
This is common and reproducible in `k8s` environment.
Try looking for a smart way to get things ready otherwise this error is very expected!

**Comment by FreeSoftwareServers** [comment] 2023-08-04 01:22
Just FYI --> https://github.com/minio/mc/issues/4651

**Comment by harshavardhana** [comment] 2023-08-04 02:37
> Just FYI --> #4651 currently can't use `_` in hostname for MinIO Server

This is completely normal and expected.
