### ISSUE TITLE
Mirror command can't detect folder

### ISSUE THREAD

**Issue by Its-Alex** [minio/mc#2472] opened 2018-06-20 13:38 UTC
## Expected behaviour

Mirror folder from minio one to minio two

## Actual behaviour

~$ mc mirror pxe-live-images/ubuntu-18.04/ pxe-live-images/ubuntu-18.04/ --overwrite~
```
$ mc mirror source/pxe-live-images/ubuntu-18.04/ dest/pxe-live-images/ubuntu-18.04/ --overwrite
mc: <ERROR> Source `source/pxe-live-images/ubuntu-18.04/` is not a folder. Only folders are supported by mirror command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

## Steps to reproduce the behaviour

I think it's because of `.` in path

## mc version

Version: 2018-06-09T02:18:09Z
Release-tag: RELEASE.2018-06-09T02-18-09Z
Commit-id: 8cf797da5fc629af4f7850858b611fc980478e2f

## System information

Mac os High Sierra

**Comment by kannappanr** [comment] 2018-06-20 18:56
@Its-Alex looking at the command, both the source and the destination are same. But the error is based only on the source.

The error can only occur, if there is no alias by the name `pxe-live-images` and there is a folder by the name `pxe-live-images` and there is a file called `ubuntu-18.04` within that folder

**Comment by Its-Alex** [comment] 2018-06-20 19:00
@kannappanr Sorry I changed path for issue but in my case, I remove alias, source and dest are not the same

For my case in source I have a folder `pxe-live-image` inside it there is a folder `ubuntu-18.04` that I want to clone in dest and this error occur.

I checked source and dest are set, folder are set too with file inside it.

All other command without dot work

**Comment by kannappanr** [comment] 2018-06-20 19:10
@Its-Alex I am unable to reproduce the issue.
```
mc mirror pxe-live-images/ubuntu-18.04/ play/ubuntu-18.04 --overwrite
pxe-live-images/ubuntu-18.04/foo.txt:                               0 B / ? ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓┃ 0s
```

**Comment by kannappanr** [comment] 2018-06-20 19:12
@Its-Alex , here is another test that I did
```
 touch pxe-live-images/ubuntu-18.05
```

```
mc mirror pxe-live-images/ubuntu-18.05/ play/ubuntu-18.04 --overwrite
mc: <ERROR> Source `pxe-live-images/ubuntu-18.05/` is not a folder. Only folders are supported by mirror command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

**Comment by kannappanr** [comment] 2018-06-20 19:14
@Its-Alex , as you can see from the previous two comments that only the source is  a local file instead of a directory will you get this error.

**Comment by Its-Alex** [comment] 2018-06-21 08:40
I show you exactly what I've done

This is my dest

```
$ mc ls dest/
[2018-06-21 10:28:11 CEST]     0B admin-scripts/
[2018-06-21 10:29:03 CEST]     0B os-images/
[2018-06-21 10:24:01 CEST]     0B pxe-live-images/
$ mc ls dest/pxe-live-images/
```
This is my source

```
$ mc ls source/pxe-live-images/
[2018-06-21 10:34:59 CEST]     0B ubuntu-16.04/
[2018-06-21 10:34:59 CEST]     0B ubuntu-18.04/
[2018-06-21 10:34:59 CEST]     0B winPE/
$ mc ls source/pxe-live-images/ubuntu-18.04
[2018-06-21 04:46:14 CEST] 241MiB filesystem.squashfs
[2018-06-21 04:46:14 CEST]  17MiB initrd.img
[2018-06-21 04:46:15 CEST] 7.9MiB vmlinuz
```

And error

```
$ mc mirror source/pxe-live-images/ubuntu-18.04/ dest/pxe-live-images/ubuntu-18.04/ --overwrite
mc: <ERROR> Source `source/pxe-live-images/ubuntu-18.04/` is not a folder. Only folders are supported by mirror command. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

**Comment by kannappanr** [comment] 2018-06-21 20:35
@Its-Alex This can happen only if you have an alias named `source` and also a local folder named `source\pxe-live-images` with a file called `ubuntu-18.04`. Can you change the location from which you run mc?

**Comment by deekoder** [comment] 2018-06-27 19:21
ping @Its-Alex we are not able to get this error. We have tried quite a bit.  Can you show `mc config host list`.

**Comment by Its-Alex** [comment] 2018-06-29 09:07
I will try to provide an environment with same error in few days, sorry for late responses

**Comment by deekoder** [comment] 2018-08-03 22:43
@Its-Alex we will close this as working as intended. Please reopen again when you are able to.

**Closed by deekoder** 2018-08-03 22:43 UTC
Labels: community, priority: medium, working as intended
