### ISSUE TITLE
mc cp Music/*.ogg s3/jukebox/ command does not work

### ISSUE THREAD

**Issue by thalesac** [minio/mc#2615] opened 2018-11-26 20:27 UTC
## Expected behavior
According to the `mc cp -h` command, we have the first example:
```
1. Copy a list of objects from local file system to Amazon S3 cloud storage.
      $ mc cp Music/*.ogg s3/jukebox/
```
## Actual behavior
I'm adding the bucket called `remote` and its working properly with other commands.
When I try to use the above syntax, like:
```$ mc cp /tmp/*.png remote/bucket-name/```
I get the following error:
```
mc: <ERROR> Unable to guess the type of copy operation. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
```

When I try to copy a single file it works. So maybe the `mc cp -h`  help text is outdated?
Does this feature really exists?

## Steps to reproduce the behavior
See above

## mc version
- (paste output of `mc version`)
```
Version: 2018-09-10T23:39:12Z
Release-tag: RELEASE.2018-09-10T23-39-12Z
Commit-id: c352cadd4be2c6bed64884c78d1e8a8ac6efaf3f```

## System information
Ubuntu 18.04

**Comment by harshavardhana** [comment] 2018-11-26 20:32
This works fine

```
~ mc cp *.md play/wal/
README.md:                      14.60 KB / 14.60 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 195.46 KB/s 0s
```

From what it looks like you don't have the `png` files
```
~ mc cp ~/Pictures/*.png play/wal/
...om 2018-11-05 13-03-41.png:  7.85 MB / 7.85 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 2.34 MB/s 3s
```
```

**Comment by thalesac** [comment] 2018-11-26 20:33
Thanks @harshavardhana . What's your `mc version` output?

**Comment by thalesac** [comment] 2018-11-26 20:39
I'm asking because that used to work for me, but not with this version I suppose. 
Or I'm not sure what I'm doing wrong. I'm happy to screenshare if you don't believe me :)

**Comment by harshavardhana** [comment] 2018-11-26 21:35
My mc version is latest master source compiled

**Comment by deekoder** [comment] 2018-11-26 21:38
@thalesac please tell us if this is the case with the latest released mc

**Comment by thalesac** [comment] 2018-11-26 21:44
I just updated my version and now I'm using the latest release, which is 
```
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511
```
I just recorded a video showing the problem:
https://youtu.be/rB8pbl3S0Hg

**Comment by deekoder** [comment] 2018-11-26 21:45
ok @thalesac  it does look like a bug to me.

**Comment by kannappanr** [comment] 2018-11-28 00:01
@thalesac I tried to reproduce the issue but was unable to do so. I used the latest master and the released version of `mc`. Can you run the same command with `--debug` option and paste the result here? We can take it from there.

**Comment by thalesac** [comment] 2018-11-28 02:18
I'm using bash (from Ubuntu 18.04)
```
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
```
Looking the debug it looks something to do with permissions in the bucket?
The `awscli s3 cp` works though.

```
$ mc cp *.png remote/comet-client/ --debug
mc: <DEBUG> GET /comet-client/?location= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-11-06T01:12:20Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181128/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**                                      
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20181128T021258Z
Accept-Encoding: gzip                   

mc: <DEBUG> HTTP/1.1 200 OK                                                                                                                   
Transfer-Encoding: chunked                      
Content-Type: application/xml                                                                                                                                    
Date: Wed, 28 Nov 2018 02:13:00 GMT       
Server: AmazonS3
X-Amz-Id-2: D7uaY9Kf71jKQzJWXHlc/APD2ngpMlL8ejzrBI7XBQLZLO2Dk1ZipDE7SRf/bKi89URo/bbAQ9g=
X-Amz-Request-Id: 52FD80711625228D

mc: <DEBUG> Response Time:  732.366126ms

mc: <DEBUG> HEAD / HTTP/1.1
Host: comet-client.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-11-06T01:12:20Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181128/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181128T021259Z

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 28 Nov 2018 02:13:00 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: GJFTcROfLOmfAVEJ0L8OGkx0DrRzxxfLb2vXFLjPAgqrnEm60+rHMQ3VmDLMBZLKoHsq2ApKb9c=
X-Amz-Request-Id: F0C613ED4FDCDA4E


mc: <DEBUG> Response Time:  647.200872ms

mc: <DEBUG> GET / HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.8 mc/2018-11-06T01:12:20Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20181128/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20181128T021259Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 28 Nov 2018 02:12:59 GMT
Server: AmazonS3
X-Amz-Id-2: xUHAqRPMr26CIPVluPG7MguB+/p1g6MZGMLR7/M/uUET5NqV4wrG1ex6phM3vM9zgDH2cFOleAQ=
X-Amz-Request-Id: BDA812DA1F2E0B6C

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>BDA812DA1F2E0B6C</RequestId><HostId>xUHAqRPMr26CIPVluPG7MguB+/p1g6MZGMLR7/M/uUET5NqV4wrG1ex6phM3vM9zgDH2cFOleAQ=</HostId></Error>
0

mc: <DEBUG> Response Time:  158.217745ms

mc: <ERROR> Unable to guess the type of copy operation. Invalid arguments provided, please refer `mc <command> -h` for relevant documentation.
 (0) cp-url-syntax.go:60 cmd.checkCopySyntax(..)
 Release-Tag:RELEASE.2018-11-06T01-12-20Z | Commit:b827fac6356f | Host:thales-desktop | OS:linux | Arch:amd64 | Lang:go1.10.2 | Mem:3.1MB/11MB | Heap:3.1MB/6.5MB
```

**Comment by thalesac** [comment] 2018-11-28 02:21
@deekoder yes, regular `cp *.png /tmp` works normally.

**Comment by thalesac** [comment] 2018-11-28 02:32
Just an Update: I added the target s3 bucket with an admin-like AWS Keys and it worked, so I guess is something to do with Permissions. I'm going to paste the policy I have for that user so you can reproduce.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:HeadBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::comet-client/*",
                "arn:aws:s3:::comet-client"
            ]
        }
    ]
}
```

**Comment by harshavardhana** [comment] 2018-12-31 08:30
We shall document this https://github.com/minio/mc/issues/2637 closing this issue.

**Closed by harshavardhana** 2018-12-31 08:30 UTC
Labels: community, priority: medium, working as intended
