### ISSUE TITLE
SIGSEGV on `mc cat`

### ISSUE THREAD

**Issue by ysimonson** [minio/mc#3219] opened 2020-05-15 15:47 UTC
## Expected behavior

`mc cat` should either return object contents, or error out.

## Actual behavior

It can panic:

```
$ mc ls s2/test-minio-bin/
[1969-12-31 19:00:00 EST]   65MiB large
[1969-12-31 19:00:00 EST]    173B small

$ mc cat s2/test-minio-bin/small
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x46fcb8]

$ mc cp s2/test-minio-bin/small small
mc: <ERROR> Unable to validate source s2/test-minio-bin/small

goroutine 65 [running]:
io.ReadAtLeast(0x0, 0x0, 0xc000398000, 0x8000, 0x8000, 0x8000, 0x14, 0x0, 0xc000312a80)
	io/io.go:310 +0x58
io.ReadFull(...)
	io/io.go:329
github.com/minio/minio-go/v6.Client.getObjectWithContext.func1(0xc0002c0180, 0xc0002c01e0, 0xc0002c0240, 0xc0002a6450, 0xc0002b25a0, 0xc000396500, 0xf7f260, 0xc0000e81a8, 0xc000376251, 0xe, ...)
	github.com/minio/minio-go/v6@v6.0.56-0.20200502013257-a81c8c13cc3f/api-get-object.go:109 +0x479
created by github.com/minio/minio-go/v6.Client.getObjectWithContext
	github.com/minio/minio-go/v6@v6.0.56-0.20200502013257-a81c8c13cc3f/api-get-object.go:66 +0x346
```

## Extra context

This is being run against a custom-written s3 store. There's probably something wrong with the custom store, but I'm guessing `mc` isn't expected to panic, even for buggy s3 implementations.

[Relevant code in minio-go.](https://github.com/minio/minio-go/blob/a81c8c13cc3f06539692c3be25fff218da98f4c7/api-get-object.go#L109)

## mc --version

```
mc version RELEASE.2020-05-06T18-00-07Z
```

## System information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by harshavardhana** [comment] 2020-05-15 16:00
Paste mc --debug output

**Comment by ysimonson** [comment] 2020-05-15 16:00
Some extra context, in case it's helpful:

Output from `mc --debug cp s2/test-minio-bin/small small`:

```
mc: <DEBUG> GET /test-minio-bin/?location= HTTP/1.1
Host: localhost:8080
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-06T18:00:07Z
Authorization: AWS4-HMAC-SHA256 Credential=homer/20200515/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200515T155507Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 139
Content-Type: application/xml
Date: Fri, 15 May 2020 15:55:07 GMT
X-Amz-Id-2: 24f988a1-65da-4bc9-8f3c-1233865b0a9c
X-Amz-Request-Id: 24f988a1-65da-4bc9-8f3c-1233865b0a9c

mc: <DEBUG> Response Time:  1.903896ms

mc: <DEBUG> HEAD /test-minio-bin/small HTTP/1.1
Host: localhost:8080
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-06T18:00:07Z
Authorization: AWS4-HMAC-SHA256 Credential=homer/20200515/pachydermia/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200515T155507Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 173
Accept-Ranges: bytes
Content-Type: text/plain; charset=utf-8
Date: Fri, 15 May 2020 15:55:07 GMT
Etag: "1cdf9415163b064f072cdca450f29103"

mc: <DEBUG> Response Time:  1.465004ms

mc: <ERROR> Unable to validate source s2/test-minio-bin/small
```

Output from `mc stat s2/test-minio-bin/small`:

```
Name      : small
Date      : 1969-12-31 19:00:00 EST 
Size      : 173 B  
ETag      : 1cdf9415163b064f072cdca450f29103 
Type      : file 
```

**Comment by ysimonson** [comment] 2020-05-15 16:08
Output from `mc --debug cat s2/test-minio-bin/small`:

```
mc: <DEBUG> GET /test-minio-bin/?location= HTTP/1.1
Host: localhost:8080
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-06T18:00:07Z
Authorization: AWS4-HMAC-SHA256 Credential=homer/20200515/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200515T160727Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 139
Content-Type: application/xml
Date: Fri, 15 May 2020 16:07:27 GMT
X-Amz-Id-2: 80e78cd2-0562-4373-bc4f-207443778b86
X-Amz-Request-Id: 80e78cd2-0562-4373-bc4f-207443778b86

mc: <DEBUG> Response Time:  1.892263ms

mc: <DEBUG> HEAD /test-minio-bin/small HTTP/1.1
Host: localhost:8080
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-06T18:00:07Z
Authorization: AWS4-HMAC-SHA256 Credential=homer/20200515/pachydermia/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200515T160727Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 173
Accept-Ranges: bytes
Content-Type: text/plain; charset=utf-8
Date: Fri, 15 May 2020 16:07:27 GMT
Etag: "1cdf9415163b064f072cdca450f29103"

mc: <DEBUG> Response Time:  1.308996ms

mc: <DEBUG> GET /test-minio-bin/small HTTP/1.1
Host: localhost:8080
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/2020-05-06T18:00:07Z
Authorization: AWS4-HMAC-SHA256 Credential=homer/20200515/pachydermia/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200515T160727Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 173
Accept-Ranges: bytes
Content-Type: text/plain; charset=utf-8
Date: Fri, 15 May 2020 16:07:27 GMT
Etag: "1cdf9415163b064f072cdca450f29103"

mc: <DEBUG> Response Time:  975.562µs

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x46fcb8]

goroutine 56 [running]:
io.ReadAtLeast(0x0, 0x0, 0xc0000a8000, 0x8000, 0x8000, 0x8000, 0x14, 0x0, 0xc000340090)
	io/io.go:310 +0x58
io.ReadFull(...)
	io/io.go:329
github.com/minio/minio-go/v6.Client.getObjectWithContext.func1(0xc0003964e0, 0xc000396540, 0xc0003965a0, 0xc000394340, 0xc0003c23c0, 0xc0003f2820, 0xf7f260, 0xc00003a298, 0xc0003b60d1, 0xe, ...)
	github.com/minio/minio-go/v6@v6.0.56-0.20200502013257-a81c8c13cc3f/api-get-object.go:109 +0x479
created by github.com/minio/minio-go/v6.Client.getObjectWithContext
	github.com/minio/minio-go/v6@v6.0.56-0.20200502013257-a81c8c13cc3f/api-get-object.go:66 +0x346
```

**Comment by ebozduman** [comment] 2020-07-08 13:13
@ysimonson 

Our code base changed quite a bit recently, like `getObjectWithContext` function is removed completely.

Could you rerun the same steps with the latest mc, preferably you build from the top of the mc branch, if not with the latest mc release, to see if there is any change in the behavior? If you can reproduce, please copy/paste the panic messages again.

In the meantime, I will be debugging May 6th code to diagnose the issue.
Thank you for your help and time.

**Comment by ysimonson** [comment] 2020-07-08 13:44
We made a bunch of changes on our side as well, and can no longer reproduce the issue even with the May 6 version.

**Comment by klauspost** [comment] 2020-07-08 13:49
@ebozduman 

This can return nil error and a nil ReadCloser: https://github.com/minio/minio-go/blob/097caa7760c782f9f7c238eebf593aa404b2ef35/api-get-object.go#L639

It seems reasonable to also return the error here. Maybe @harshavardhana knows more - seems to be last changed in #1245

If it is expected all callers should check if the returned ReadCloser is nil.

**Comment by ebozduman** [comment] 2020-07-09 09:55
Thanks @klauspost for the hint.

This is exactly where we trip over if something goes wrong when `ToObjectInfo(bucketName, objectName, resp.Header)` is called and returns an error.

I instigated an error at this point and checked if I can reproduce the crash.
```
	objectStat, err := ToObjectInfo(bucketName, objectName, resp.Header)
	err = errors.New("Error: Forced error here to reproduce the panic")
	if err != nil {
		closeResponse(resp)
		return nil, objectStat, resp.Header, err
	}
```

It crashed when I ran my `test-getObject.go` script, which is exactly the same test with `examples/s3/getobject.go` only adjusted to run against my local minio server instead of s3.

```
$ go run examples/s3/test-getobject.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x48d738]

goroutine 6 [running]:
io.ReadAtLeast(0x0, 0x0, 0xc000284300, 0x1a, 0x1a, 0x1a, 0x0, 0x0, 0xc0001cfaa0)
	/usr/local/go/src/io/io.go:310 +0x58
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
github.com/minio/minio-go/v7.Client.GetObject.func1(0xc0000323c0, 0xc000032420, 0xc000032480, 0xc000021e20, 0xc0001cfb30, 0xc000136370, 0x94d8e0, 0xc00002c110, 0x89f703, 0x4, ...)
	/home/ersan/work/src/github.com/minio/minio-go/api-get-object.go:195 +0xd99
created by github.com/minio/minio-go/v7.Client.GetObject
	/home/ersan/work/src/github.com/minio/minio-go/api-get-object.go:62 +0x346
exit status 2
```
If `resp.Body` value was returned instead of `nil`, it would still be ok and the program would exit gracefully instead of a panic and the error message would be : `read on closed response body`.

```
$ go run examples/s3/test-getobject.go 
2020/07/09 02:41:54 http: read on closed response body
exit status 1
```
However, the best thing is to stop at the right place when error happened.

```
$ go run examples/s3/test-getobject.go 
2020/07/09 02:10:55 Error: Forced error here to reproduce the panic
exit status 1
```
So, the fix is to return the error right away when it happens.

**Comment by ebozduman** [comment] 2020-07-14 21:47
@ysimonson,

Closing the issue.

**Closed by ebozduman** 2020-07-14 21:47 UTC
Labels: community, priority: low
