### ISSUE TITLE
mc: <ERROR> Failed to copy

### ISSUE THREAD

**Issue by douglasmccormickjr** [minio/mc#1549] opened 2015-12-13 20:29 UTC
I've tried many different techniques to get this to work -- I'm getting a timeout error...here's some of the console output:

```
./mc cp --recursive /Users/<pathway-to-images>/ https://dougs-apple-air-001.s3-website-us-west-2.amazonaws.com/

mc: <ERROR> Failed to copy ‘/Users/<pathway-to-images>/IMG_8080.PNG’. dial tcp 54.231.184.171:443: i/o timeout
mc: Session safely terminated. To resume session ‘mc session resume zamtoRAd’
```

FYI -- dougs-apple-air-001 is the name of my s3 bucket (maybe I'm screwing things up with using the wrong bucket url? I don't know really)

Any help would be greatly appreciated.  Thanks so much,
-Doug Jr.

**Comment by harshavardhana** [comment] 2015-12-13 20:50
> ./mc cp --recursive /Users/<pathway-to-images>/ https://dougs-apple-air-001.s3-website-us-west-2.amazonaws.com/

I think the issue is in the URL since S3 website endpoints should not be used in this way. Also http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region - website endpoints do not support HTTPS so it is not an ideal way to transfer the data into your bucket. 

It is better to use simply 

```./mc cp --recursive /Users/<pathway-to-images>/ https://dougs-apple-air-001.s3-us-west-2.amazonaws.com/```

**Comment by harshavardhana** [comment] 2015-12-14 19:11
@douglasmccormickjr  - were you able to verify my previous comment? . Let me know if you are still facing issues.

**Comment by harshavardhana** [comment] 2016-01-09 05:30
Closing.. due to in-activity.

**Closed by harshavardhana** 2016-01-09 05:30 UTC
