### ISSUE TITLE
Google Cloud Storage gives "The request signature we calculated does not match the signature you provided" since RELEASE.2023-04-12T02-21-51Z

### ISSUE THREAD

**Issue by tigitz** [minio/mc#4552] opened 2023-04-17 09:48 UTC
## Expected behavior
No error
## Actual behavior
```
mc: <ERROR> Unable to read from `gcs/bucket-name/file`. The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```
## Steps to reproduce the behavior
With the same credentials, this doesn't work
```sh
docker run --rm -ti -e MC_HOST_gcs=rotating_credentials minio/mc:RELEASE.2023-04-12T02-21-51Z cat gcs/bucket-name/file 
```
But this works
```sh
docker run --rm -ti -e MC_HOST_gcs=rotating_credentials minio/mc:RELEASE.2023-04-06T16-51-10Z cat gcs/bucket-name/file 
```

**Comment by harshavardhana** [comment] 2023-04-17 16:33
Closing as duplicate of #4547

**Closed by harshavardhana** 2023-04-17 16:33 UTC
Labels: community, triage
