### ISSUE TITLE
heal stuck on certain files

### ISSUE THREAD

**Issue by philipkozeny** [minio/mc#2576] opened 2018-10-19 11:02 UTC
I am running minio on 3 servers (Debian 9, binary, distributed mode) with 6 disks in total. For testing purposes I have uploaded around 40 GB of small encrypted files. 

When I am running the heal command the heal process seems stuck for ~10-15 minutes on some files (always the same files). In some cases the heal process ends with an error, and most times after 30-40 minutes the heal process finishes.

I tried to delete the whole bucket and reupload everything. Running the heal command again I can see that it is "stuck" at the same file. The file is around ~300kb in size. 

Is there any information I can provide to debug the situation? Running the heal command with --debug doesn't seem to show anything useful, except that it is getting a 200 response with the same information. If I download that file and create a new bucket alone the heal process is running through in a few seconds, so not 100% sure there is an issue with that file.

## mc version

> Version: 2018-10-18T00:40:05Z
> Release-tag: RELEASE.2018-10-18T00-40-05Z
> Commit-id: 0dd32c1b26f05e7f94f76f2ceb62b5229836b009

## System information

> minio
> Version: 2018-10-18T00:28:58Z
> Release-Tag: RELEASE.2018-10-18T00-28-58Z
> Commit-ID: 3b553570459cdf8b10671105252c707ff2cf76f3

**Comment by philipkozeny** [comment] 2018-10-25 09:09
@vadmeste yes, from all three hosts with `mc cp`

**Comment by philipkozeny** [comment] 2018-10-25 13:28
@vadmeste I've run the command now with --json as output. Heal stopped responding with JSON output on the last file status. after some minutes it returned the error:

```
{
    "after": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "before": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "name": "demo/58/ec11d1aa-6256-48b0-b5bc-7fed8623ca87",
    "size": 316342,
    "status": "success",
    "type": "object"
}
{
    "error": {
        "cause": {
            "error": {
                "BucketName": "",
                "Code": "XMinioHealNoSuchProcess",
                "HostID": "3L137",
                "Key": "",
                "Message": "No such heal process is running on the server",
                "Region": "",
                "RequestID": "1560DCC2F90CCFD2"
            },
            "message": "No such heal process is running on the server"
        },
        "message": "Unable to display follow heal status.",
        "sysinfo": {
            "host.arch": "amd64",
            "host.cpus": "8",
            "host.lang": "go1.10.2",
            "host.name": "storage-2",
            "host.os": "linux",
            "mem.heap.total": "8.4MB",
            "mem.heap.used": "1.9MB",
            "mem.total": "14MB",
            "mem.used": "1.9MB"
        },
        "type": "error"
    },
    "status": "error"
}
```

**Comment by vadmeste** [comment] 2018-10-25 15:44
Thanks @philipkozeny, would you try again to heal that particular file, print the mc json output as long with any output that you see in Minio server ?

**Comment by philipkozeny** [comment] 2018-10-26 21:43
@vadmeste if I only heal the smaller folder that contains that file, or that file directly there is no problem at all.

What I have recognised although ist that the heal always stopped after the file that failed the last time. Now it is no longer always the same one. I have started it three times, and two times it was a different file after the one above where it stopped. One time it ran through after stopping for about 10-15 minutes.

When it ran through this is the last output: 

> {"status":"success","type":"summary","objects_scanned":199624,"objects_healed":0,"items_scanned":199631,"items_healed":0,"size":45533436975,"duration":1777}

This is the output from one of those files:

```
user@storage-2:~$ ./mc admin heal local/demo/58/f1d9f68c-2186-48b5-ad91-32ff0fce3295 --json
{
    "after": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "23e58e0f-64cf-4db6-8dab-bfb194d93148"
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "dab074a1-742a-4187-ac28-3aeb01a8a674"
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "8ace5ade-e97c-46b5-976d-7e1eeb3c3d10"
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "08c50b42-2526-4460-b4d4-e378d6cae4c2"
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "1bc28dcd-0ba9-4501-aa37-314f6138fbfd"
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "2205e4fb-896e-4534-ad89-cc370ae5a7fd"
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "before": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "23e58e0f-64cf-4db6-8dab-bfb194d93148"
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "dab074a1-742a-4187-ac28-3aeb01a8a674"
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": "8ace5ade-e97c-46b5-976d-7e1eeb3c3d10"
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "08c50b42-2526-4460-b4d4-e378d6cae4c2"
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "1bc28dcd-0ba9-4501-aa37-314f6138fbfd"
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": "2205e4fb-896e-4534-ad89-cc370ae5a7fd"
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "name": "disk-format",
    "size": 0,
    "status": "success",
    "type": "system"
}
{
    "after": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "before": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "name": "bucket-metadata:.minio.sys/config/config.json",
    "size": 0,
    "status": "success",
    "type": "system"
}
{
    "after": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-1",
                "state": "offline",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-2",
                "state": "offline",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 2,
        "online": 6
    },
    "before": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-1",
                "state": "offline",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.11:9000/mnt/storage-2",
                "state": "offline",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 2,
        "online": 6
    },
    "name": "demo/",
    "size": 0,
    "status": "success",
    "type": "bucket"
}
{
    "after": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "before": {
        "color": "green",
        "corrupted": 0,
        "drives": [
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-1",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.10:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            },
            {
                "endpoint": "http://192.168.100.12:9000/mnt/storage-2",
                "state": "ok",
                "uuid": ""
            }
        ],
        "missing": 0,
        "offline": 0,
        "online": 6
    },
    "name": "demo/58/f1d9f68c-2186-48b5-ad91-32ff0fce3295",
    "size": 249698,
    "status": "success",
    "type": "object"
}
{
    "duration": 2,
    "items_healed": 0,
    "items_scanned": 4,
    "objects_healed": 0,
    "objects_scanned": 1,
    "size": 249698,
    "status": "success",
    "type": "summary"
}
```

Similar output if i run it on the 58 folder with --recursive.

From minio itself i see no output in the console, is there a debug mode or anything I can activate?

**Comment by vadmeste** [comment] 2018-11-02 13:11
@philipkozeny do you have time for a private chat about this issue? I am not able to reproduce it locally so I need more information.

**Comment by philipkozeny** [comment] 2018-11-03 10:54
@vadmeste sure, just tell me when you are available and where to contact you.

**Comment by vadmeste** [comment] 2018-11-05 10:40
@philipkozeny could me ping me here https://slack.minio.io, my timezone is GMT+1

**Comment by vadmeste** [comment] 2018-11-06 21:03
@philipkozeny confirmed that healing is not failing anymore with the new release (after @harshavardhana last refactor) but still seems to take a considerable time with one object (not a specific object), which makes mc looks like frozen.

**Comment by philipkozeny** [comment] 2018-11-07 09:16
@vadmeste sorry to report again but healing is again failing with the latest release. 

> mc: <ERROR> Unable to display heal status. No such heal process is running on the server

**Comment by vadmeste** [comment] 2018-11-07 10:16
> @vadmeste sorry to report again but healing is again failing with the latest release.
> 
> > mc:  Unable to display heal status. No such heal process is running on the server

I was able to see this, can you open a new issue for this ?

**Comment by vadmeste** [comment] 2018-11-07 10:16
> I was able to see this, can you open a new issue for this ?

I am currently debugging it and seeing how to fix this.

**Comment by vadmeste** [comment] 2018-11-07 16:40
@philipkozeny are you using a load balancer ? one workaround then is to call mc heal directly to  one node.

Also there is another scenario, more rare which generates the same error message. I am going to send a PR for it shortly.

**Comment by philipkozeny** [comment] 2018-11-08 07:37
@vadmeste yes, but i am running mc locally on one of the machines and access it via 127.0.0.1

**Comment by vadmeste** [comment] 2019-02-06 23:18
> Also there is another scenario, more rare which generates the same error message. I am going to send a PR for it shortly.

@philipkozeny I believe this issue is fixed with this PR https://github.com/minio/minio/commit/7b579caf686110d96349ec4e90beacf7eed5af89, please reopen if you still see the issue

**Closed by vadmeste** 2019-02-06 23:18 UTC
Labels: priority: medium, triage
