### ISSUE TITLE
   mc policy display custom  not none 

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [minio/mc#3269] opened 2020-06-23 08:24 UTC
## Expected behavior
[root@minio1 ~]#  /opt/mc policy list  minio1/mmsvideo
mmsvideo/2020* => readwrite
[root@minio1 ~]# /opt/mc policy set none minio1/mmsvideo/

## Actual behavior
[root@minio1 ~]# /opt/mc policy get minio1/mmsvideo
Access permission for `minio1/mmsvideo` is `custom`

## Steps to reproduce the behavior
[root@minio1 ~]#/opt/mc policy set none minio1/mmsvideo/
[root@minio1 ~]# /opt/mc policy get minio1/mmsvideo
Access permission for `minio1/mmsvideo` is `custom`

## mc --version
- (paste output of `mc --version`)
[root@minio1 ~]# /opt/mc --version
mc version RELEASE.2020-04-04T05-28-55Z

## System information
[root@minio1 ~]# uname -a
Linux minio1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
You have mail in /var/spool/mail/root
[root@minio1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@minio1 ~]#

**Comment by kannappanr** [comment] 2020-06-27 08:19
@Blue-Skies-firststar Unable to reproduce the issue with the latest as well as the version specified. Can you repro the issue against `play`?

**Comment by Blue-Skies-firststar** [comment] 2020-06-28 02:30
[root@minio1 opt]# /opt/minio -version
minio version RELEASE.2020-04-04T05-39-31Z
[root@minio1 opt]# /opt/mc -version
mc version RELEASE.2020-04-04T05-28-55Z
I  can reproduce the issue if  the bucket is not  empty
the minio1/arcvideo is empty and the minio1/mmsvideo is not empty,  you can see the difference, 
the  minio1/arcvideo is normal
if the  bucket  policy is  custom that I can accessible without verification  as well as public but I want none 

1.
[root@minio1 mmsvideo]# /opt/mc policy set public minio1/arcvideo
Access permission for `minio1/arcvideo` is set to `public`
[root@minio1 mmsvideo]# /opt/mc policy get minio1/arcvideo
Access permission for `minio1/arcvideo` is `public`
[root@minio1 mmsvideo]# /opt/mc policy set none minio1/arcvideo
Access permission for `minio1/arcvideo` is set to `none`
[root@minio1 mmsvideo]# /opt/mc policy get  minio1/arcvideo
Access permission for `minio1/arcvideo` is `none`

2.
[root@minio1 mmsvideo]# /opt/mc policy set public minio1/mmsvideo
Access permission for `minio1/mmsvideo` is set to `public`
You have mail in /var/spool/mail/root
[root@minio1 mmsvideo]# /opt/mc policy get minio1/mmsvideo
Access permission for `minio1/mmsvideo` is `public`
[root@minio1 mmsvideo]# /opt/mc policy set none minio1/mmsvideo
Access permission for `minio1/mmsvideo` is set to `none`
[root@minio1 mmsvideo]# /opt/mc policy get   minio1/mmsvideo
Access permission for `minio1/mmsvideo` is `custom`

**Comment by vadmeste** [comment] 2020-06-29 08:29
@Blue-Skies-firststar could you paste the output of this command: `mc policy get-json myminio1/mmsvideo` ?

**Comment by Blue-Skies-firststar** [comment] 2020-06-30 05:49
I think I found the reason for this problem，It has nothing to do with whether the bucket is empty
Because a certain directory of the bucket is readable or writable, the bucket cannot be completely closed for access

**Comment by vadmeste** [comment] 2020-06-30 10:02
> It is first confirm that the subdirectories in the bucket are none , This bucket can be none

Yes, so this is how to reproduce:

```
$ mc policy get play/random-bucket/
=> None
$ mc policy set public play/random-bucket/dir/
=> Public
$ mc policy get play/random-bucket/
=> Custom
```

Maybe what we need to do is to add a informal message which says there are other custom policies are set when doing this:

```
mc policy set none play/random-bucket/
```

**Comment by kannappanr** [comment] 2020-07-01 06:18
closing this issue as this behavior is expected. Please feel free to reach out to us if you have further questions.

**Closed by kannappanr** 2020-07-01 06:18 UTC
Labels: community, working as intended
