### ISSUE TITLE
Heal Operation Timeouts

### ISSUE THREAD

**Issue by eyalrif** [minio/mc#2582] opened 2018-10-25 05:57 UTC
## Expected behavior
I have a setup of 8 servers with 96 disks (12 on each server).The object size i am using is 1MB and the amount of objects is around 5M. when running heal operation on a single object - i get a timeout

`
/usr/local/bin/mc admin heal --json --recursive Minio/wekabucket1/358adf34/d/d/95/20/3696
....
{"status":"success","type":"system","name":"bucket-metadata:.minio.sys/config/config.json","before":{"color":"green","offline":0,"online":8,"missing":0,"corrupted":0,"drives":[{"uuid":"","endpoint":"/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.2:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.3:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.4:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.5:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.6:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.7:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.8:9000/minio/minio_drive10","state":"ok"}]},"after":{"color":"green","offline":0,"online":8,"missing":0,"corrupted":0,"drives":[{"uuid":"","endpoint":"/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.2:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.3:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.4:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.5:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.6:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.7:9000/minio/minio_drive10","state":"ok"},{"uuid":"","endpoint":"http://172.21.8.8:9000/minio/minio_drive10","state":"ok"}]},"size":0}
Heal had an error -  Operation timed out:
{"status":"success","type":"summary","objects_scanned":0,"objects_healed":0,"items_scanned":2,"items_healed":0,"size":0,"duration":1861}
`

mc ls operation returns in reasonable time:

[root@xxxxx-wekabe-1 minio]# time mc ls Minio/wekabucket1/358adf34/d/d/95/20/3696
[2018-10-24 13:30:47 IDT] 296KiB 50ef-4da8-ade2-02eae1f8ba36

real	0m3.420s
user	0m0.015s
sys	0m0.008s

## mc version

Version: 2018-10-18T00:40:05Z
Release-tag: RELEASE.2018-10-18T00-40-05Z
Commit-id: 0dd32c1b26f05e7f94f76f2ceb62b5229836b009

[root@xxxx-wekabe-1 minio]# minio version
Version: 2018-10-18T00:28:58Z
Release-Tag: RELEASE.2018-10-18T00-28-58Z
Commit-ID: 3b553570459cdf8b10671105252c707ff2cf76f3

## System information
8 servers - 12 disks per server (10TB each disk)

**Comment by harshavardhana** [comment] 2018-10-25 06:12
thanks @eyalrif we will take a look

**Comment by harshavardhana** [comment] 2018-11-02 18:06
I am not able to reproduce this issue @eyalrif - but we bringing a few features to be able to stop healing on a prefix. https://github.com/minio/mc/pull/2584

**Comment by kannappanr** [comment] 2018-11-08 01:31
PR #2584 has been merged. Closing the issue with #2854 being a way to handle this issue. Please let us know if you have any concerns.

**Closed by kannappanr** 2018-11-08 01:31 UTC
Labels: priority: medium, triage
