### ISSUE TITLE
mc crash "runtime: epollwait on fd 13 failed with 9"

### ISSUE THREAD

**Issue by rob-killingsworth** [minio/mc#2270] opened 2017-10-04 15:00 UTC
Crash in mc

This is on an upload command and is very intermittent. The server side logs don't show any errors
mc version 2017-02-06T20:16:19Z

mc -q cp build/DEVELOPMENT/Release/INTEL_64_LINUX/PyDist-DEVELOPMENT-79752-22.41.p004-Linux-x86_64.R.tar.gz datastore///79752/

```
runtime: epollwait on fd 13 failed with 9
fatal error: epollwait failed
runtime stack:
runtime.throw(0x8a6994, 0x10)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:566 +0x95
runtime.netpoll(0xacc300, 0x8f1b9619d61c8)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/netpoll_epoll.go:71 +0x13d
runtime.sysmon()
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/proc.go:3633 +0x3e7
runtime.mstart1()
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/proc.go:1126 +0x11e
runtime.mstart()
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/proc.go:1096 +0x64
goroutine 1 [chan receive]:
github.com/minio/mc/cmd.(*s3Client).Stat(0xc4201f8a00, 0x0, 0x0, 0x0)
	/home/builder/mygo/src/github.com/minio/mc/cmd/client-s3.go:847 +0x6e3
github.com/minio/mc/cmd.url2Stat(0x7fff2edf3b79, 0x34, 0x0, 0x34, 0x0, 0x479a5e)
	/home/builder/mygo/src/github.com/minio/mc/cmd/client-url.go:179 +0x11e
github.com/minio/mc/cmd.isTargetURLDir(0x7fff2edf3b79, 0x34, 0xaa0720)
	/home/builder/mygo/src/github.com/minio/mc/cmd/common-methods.go:30 +0x39
github.com/minio/mc/cmd.guessCopyURLType(0xc42000a120, 0x1, 0x2, 0x7fff2edf3b79, 0x34, 0x0, 0xc420171658, 0x401291)
	/home/builder/mygo/src/github.com/minio/mc/cmd/cp-url.go:68 +0x9e
github.com/minio/mc/cmd.checkCopySyntax(0xc42006f8c0)
	/home/builder/mygo/src/github.com/minio/mc/cmd/cp-url-syntax.go:58 +0x345
github.com/minio/mc/cmd.mainCopy(0xc42006f8c0, 0x0, 0x2006f8c0)
	/home/builder/mygo/src/github.com/minio/mc/cmd/cp-main.go:359 +0x2f
github.com/minio/mc/vendor/github.com/minio/cli.HandleAction(0x81da20, 0x8e8dd0, 0xc42006f8c0, 0xc420055700, 0x0)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:491 +0xd4
github.com/minio/mc/vendor/github.com/minio/cli.Command.Run(0x8a0ddc, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9f37, 0x17, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/command.go:212 +0xb9a
github.com/minio/mc/vendor/github.com/minio/cli.(*App).Run(0xc4200e56c0, 0xc42000a0f0, 0x5, 0x5, 0x0, 0x0)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:256 +0x816
github.com/minio/mc/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc4200e56c0)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:277 +0x53
github.com/minio/mc/cmd.Main()
	/home/builder/mygo/src/github.com/minio/mc/cmd/main.go:89 +0x163
main.main()
	/home/builder/mygo/src/github.com/minio/mc/main.go:28 +0x14
goroutine 5 [chan receive]:
github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420054480, 0xc4200543c0)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x5a
created by github.com/minio/mc/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x181
goroutine 6 [chan receive]:
github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420054480, 0xc420054420)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x94
created by github.com/minio/mc/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x1ad
goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/os/signal/signal_unix.go:28 +0x41
goroutine 8 [select]:
net/http.(*persistConn).roundTrip(0xc420081900, 0xc4201f8e80, 0x0, 0x0, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4201e85a0, 0xc4201e8780, 0xc4201e85a0, 0x0, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:380 +0x4ee
net/http.send(0xc4201e8780, 0xa98620, 0xc4201e85a0, 0x0, 0x0, 0x0, 0x8, 0xc420232598, 0xc420026390)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4201efa70, 0xc4201e8780, 0x0, 0x0, 0x0, 0xc420026390, 0x0, 0x1)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4201efa70, 0xc4201e8780, 0x8e94d8, 0x3, 0xc4201f5001, 0x8a30ac)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4201efa70, 0xc4201e8780, 0x1, 0x3b893c6200000003, 0xc420232818)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/client.go:184 +0x1ea
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.do(0xc4201f8a20, 0x4, 0x0, 0x0, 0x0, 0xc4201f8a27, 0xf, 0x0, 0x0, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api.go:405 +0x50
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.getBucketLocation(0xc4201f8a20, 0x4, 0x0, 0x0, 0x0, 0xc4201f8a27, 0xf, 0x0, 0x0, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/bucket-cache.go:106 +0x2f8
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRequest(0xc4201f8a20, 0x4, 0x0, 0x0, 0x0, 0xc4201f8a27, 0xf, 0x0, 0x0, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api.go:575 +0xb81
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.executeMethod(0xc4201f8a20, 0x4, 0x0, 0x0, 0x0, 0xc4201f8a27, 0xf, 0x0, 0x0, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api.go:489 +0x252
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.listObjectsQuery(0xc4201f8a20, 0x4, 0x0, 0x0, 0x0, 0xc4201f8a27, 0xf, 0x0, 0x0, 0x0, ...)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-list.go:386 +0x41c
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.ListObjects.func1(0xc4201977a0, 0xc4201e5652, 0x16, 0xc4201e5669, 0x12, 0x8a0c85, 0x1, 0x0, 0xc420055b00)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-list.go:291 +0x11f
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.ListObjects
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-list.go:337 +0x380
goroutine 9 [sleep]:
time.Sleep(0x35c1ac67)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/time.go:59 +0xe1
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer.func2(0xc420055c80, 0x5, 0xc420055c20, 0xc4201efb30)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:73 +0x10e
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.newRetryTimer
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/retry.go:75 +0x168
goroutine 13 [runnable]:
syscall.Syscall(0x0, 0xc, 0xc4201f1000, 0x1000, 0x180, 0x1000, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xc, 0xc4201f1000, 0x1000, 0x1000, 0x72, 0x0, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0xc, 0xc4201f1000, 0x1000, 0x1000, 0xffffffffffffff01, 0xa9a260, 0xc420012140)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/syscall/syscall_unix.go:161 +0x49
net.(*netFD).Read(0xc4201dbf80, 0xc4201f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/fd_unix.go:239 +0x10f
net.(*conn).Read(0xc420026398, 0xc4201f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420081900, 0xc4201f1000, 0x1000, 0x1000, 0x60e873, 0xc420020378, 0xc420020388)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc4202384e0)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4202384e0, 0x1, 0xc420238660, 0xc420020460, 0xc4200203c8, 0x40f808, 0x50)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420081900)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1062 +0x4e9
goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc420081900)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/net/http/transport.go:1063 +0x50e
program finished with exit code 2
```

**Comment by harshavardhana** [comment] 2017-10-04 17:22
> runtime: epollwait on fd 13 failed with 9
> fatal error: epollwait failed

from what it looks like is a Go runtime issue.

**Comment by vadmeste** [comment] 2017-10-05 20:15
@rob-killingsworth, this is a golang issue, as @harshavardhana suggested.

By the way, you are not using the latest mc version, you can download a new one from here https://minio.io/downloads.html

By the way, is there any chance that you are running Docker in the same machine? If yes, can you stop it and test again?

**Comment by deekoder** [comment] 2017-10-11 22:39
@rob-killingsworth  we need your help to do root cause analysis.

**Comment by rob-killingsworth** [comment] 2017-10-12 07:18
Hi, Since upgrading mc to the latest version I have not seen the crash in a couple of days. If there is anything else you would like me to do please let me know.

**Comment by harshavardhana** [comment] 2017-10-12 07:28
> Hi, Since upgrading mc to the latest version I have not seen the crash in a couple of days. If there is anything else you would like me to do please let me know.

Feel free to close the issue @rob-killingsworth

**Closed** 2017-10-12 08:15 UTC
Labels: priority: severe, triage
