### ISSUE TITLE
Healing result in JSON shows empty information related to an offline node

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2648] opened 2019-01-18 16:53 UTC
## Expected behavior
JSON output should show the name of the offline nodes after a heal operation.

## Actual behavior
JSON output is not showing  the name of the offline nodes after a heal operation.

## Steps to reproduce the behavior
1. Start a distributed Minio setup
2. Create one test bucket and upload one test file
3. Kill one Minio instance
4. mc admin heal --json -r myminio/testbucket/testfile
```
{
  "status": "success",
  "type": "object",
  "name": "testbucket/Dockerfile",
  "before": {
    "color": "yellow",
    "offline": 1,
    "online": 3,
    "missing": 0,
    "corrupted": 0,
    "drives": [
      {
        "uuid": "",
        "endpoint": "http://192.168.100.143:9001/mnt/p4/vadmeste/xl/1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "",
        "state": "offline"
      },
      {
        "uuid": "",
        "endpoint": "http://192.168.100.143:9003/mnt/p4/vadmeste/xl/3",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/mnt/p4/vadmeste/xl/4",
        "state": "ok"
      }
    ]
  },
  "after": {
    "color": "yellow",
    "offline": 1,
    "online": 3,
    "missing": 0,
    "corrupted": 0,
    "drives": [
      {
        "uuid": "",
        "endpoint": "http://192.168.100.143:9001/mnt/p4/vadmeste/xl/1",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "",
        "state": "offline"
      },
      {
        "uuid": "",
        "endpoint": "http://192.168.100.143:9003/mnt/p4/vadmeste/xl/3",
        "state": "ok"
      },
      {
        "uuid": "",
        "endpoint": "/mnt/p4/vadmeste/xl/4",
        "state": "ok"
      }
    ]
  },
  "size": 552
}
```

## mc version
All

## System information
All

**Comment by sinhaashish** [comment] 2019-05-21 14:30
@vadmeste  Can you help in reproducing the issue. 
I tried the below on my local machine and its seems to be working .
Ran 
```
On terminal 1
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
./minio server --config-dir /tmp/config1 --address=:9001 http://127.0.0.1:9001/tmp/dist-disk1 http://127.0.0.1:9002/tmp/dist-disk2 http://127.0.0.1:9003/tmp/dist-disk3 http://127.0.0.1:9004/tmp/dist-disk4

On terminal 2
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
./minio server --config-dir /tmp/config2 --address=:9002 http://127.0.0.1:9001/tmp/dist-disk1 http://127.0.0.1:9002/tmp/dist-disk2 http://127.0.0.1:9003/tmp/dist-disk3 http://127.0.0.1:9004/tmp/dist-disk4

On terminal 3
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
./minio server --config-dir /tmp/config3 --address=:9003 http://127.0.0.1:9001/tmp/dist-disk1 http://127.0.0.1:9002/tmp/dist-disk2 http://127.0.0.1:9003/tmp/dist-disk3 http://127.0.0.1:9004/tmp/dist-disk4

On terminal 4
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
./minio server --config-dir /tmp/config4 --address=:9004 http://127.0.0.1:9001/tmp/dist-disk1 http://127.0.0.1:9002/tmp/dist-disk2 http://127.0.0.1:9003/tmp/dist-disk3 http://127.0.0.1:9004/tmp/dist-disk4
```
Then 
uploaded the Object suing `mc`. 
Then stopped the server running on terminal 4.
After running `mc admin heal --json -r myminio/my-bucket/object`
got the below 
```
ashish@minio:~/code/go/src/github.com/minio/mc$ ./mc admin heal --json myminio/hogaya/book.txt
{
 "status": "success",
 "type": "system",
 "name": "disk-format",
 "before": {
  "color": "grey",
  "offline": 4,
  "online": 0,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9003/tmp/dist-disk3",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "after": {
  "color": "grey",
  "offline": 4,
  "online": 0,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9003/tmp/dist-disk3",
    "state": "offline"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "system",
 "name": "bucket-metadata:.minio.sys/config/config.json",
 "before": {
  "color": "yellow",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "after": {
  "color": "yellow",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "bucket",
 "name": "hogaya/",
 "before": {
  "color": "red",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "after": {
  "color": "red",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "size": 0
}
{
 "status": "success",
 "type": "object",
 "name": "hogaya/book.txt",
 "before": {
  "color": "yellow",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "after": {
  "color": "yellow",
  "offline": 1,
  "online": 3,
  "missing": 0,
  "corrupted": 0,
  "drives": [
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9001/tmp/dist-disk1",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9002/tmp/dist-disk2",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "/tmp/dist-disk3",
    "state": "ok"
   },
   {
    "uuid": "",
    "endpoint": "http://127.0.0.1:9004/tmp/dist-disk4",
    "state": "offline"
   }
  ]
 },
 "size": 5265731
}
{
 "status": "success",
 "type": "summary",
 "objects_scanned": 1,
 "objects_healed": 0,
 "items_scanned": 4,
 "items_healed": 0,
 "size": 5265731,
 "duration": 1
}
```

**Comment by vadmeste** [comment] 2019-05-21 15:37
@sinhaashish this issue was present in RELEASE.2019-01-10T00-21-20Z but currently it is not reproducible anymore, we can safely close this issue.

**Comment by nitisht** [comment] 2019-05-27 11:53
closing based on above comment

**Closed by nitisht** 2019-05-27 11:53 UTC
Labels: priority: medium
