### ISSUE TITLE
One case of wrong diff calcuation

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#2349] opened 2018-01-08 11:02 UTC
## Expected behaviour

`mc diff src/ target/` and `mc diff target/ src/` should have the same calculation result (with little direction difference)

## Actual behaviour

I have one case where `mc diff src/ target/` doesn't show any output and `mc diff target/ src/` shows some diff.

## Steps to reproduce the behaviour
```
$ mkdir dir/; touch dir/file
$ mc mb s3/mybucket
$ mc mirror dir/ s3/mybucket/
$ mc diff dir/ s3/mybucket/
(no output => no diff)
$ mc diff s3/mybucket/ dir/
! dir/file
```

## mc version
Master version

## System information
All

**Comment by ebozduman** [comment] 2018-02-05 22:59
@vadmeste, @abperiasamy, @harshavardhana and I've discussed the subject and it turned out to be the offending behavior addressed in this issue is actually by design. So, there is nothing to be fixed (reverted back PR #2374).

The reasoning/explanation behind this decision is that `mc diff` is expected to work exactly the same way as `mc mirror`, hence `mc diff` not reporting anything when target object's modification time is ahead of the source object is correct as there won't be any mirroring in this scenario.

Closing the issue with label "working as intended"

**Closed by ebozduman** 2018-02-05 22:59 UTC
Labels: priority: medium, triage, working as intended
