### ISSUE TITLE
mc copies the wrong selection in this case?

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1747] opened 2016-07-04 12:27 UTC
```
$ cd /tmp/test/
$ mkdir mc
$ touch mc_test.go
$ mc cp -r mc myminio/bucket/
[0] ◐ mc_test.go
```

**Comment by vadmeste** [comment] 2016-07-04 13:20
Probably working as expected after reviewing the code, but it is little confusing, is it possible to replace --recursive with --prefix here ?

**Comment by harshavardhana** [comment] 2016-07-04 17:56
> Probably working as expected after reviewing the code, but it is little confusing, is it possible to replace --recursive with --prefix here ?

This is because of cli related issue.

**Comment by harshavardhana** [comment] 2016-07-08 22:36
Because of this bug - https://github.com/minio/mc/issues/1513

**Comment by harshavardhana** [comment] 2016-07-08 22:37
https://github.com/minio/mc/issues/1432 and here

**Comment by harshavardhana** [comment] 2016-07-08 22:37
Closing this as duplicate of #1513

**Closed by harshavardhana** 2016-07-08 22:37 UTC
