### ISSUE TITLE
Allow the use of mc admin update in air gapped environments

### ISSUE THREAD

**Issue by MAHDTech** [minio/mc#3028] opened 2020-01-02 05:58 UTC
## Expected behavior

The mc admin update command should allow the ability to specify an internal URL and specific release for air gapped environments.

For example it could be something like;

```
mc admin update my-minio --url https://internal-mirror.internal.domain/minio --release RELEASE.2019-12-30T05-45-39Z
```

## Actual behavior

The mc admin update command attempts to download from dl.min.io directly

## Steps to reproduce the behavior

Run the following

```
mc admin update my-minio --debug

{"Code":"XMinioAdminUpdateURLNotReachable","Message":"Get https://dl.min.io/server/minio/release/linux-amd64/minio.shasum: dial tcp: lookup dl.min.io on X.X.X.X: server misbehaving","Resource":"/minio/admin/v2/update","RequestId":"XXXXX","HostId":"XXXXX"}
mc: <DEBUG> Response Time:  2.04021018s
```

## mc --version

mc version RELEASE.2019-12-24T23-41-36Z

## System information

MinIO running on RHEL 7.7

## Other

This is useful for environments which have no internet access and may be using solutions like nexus or artifactory to store internal downloads.

**Comment by nitisht** [comment] 2020-01-02 05:59
Thanks for reporting, we'll take a look @MAHDTech

**Comment by harshavardhana** [comment] 2020-01-02 06:09
@MAHDTech `mc admin update` already allows custom URL the problem is you need to follow certain guidelines - in terms of how to create a mirror. 

Also, it's on purpose not documented right now @MAHDTech so if you create a mirror-like `dl.minio.io` it works easily.

So all you have to do is have the same directory structure such as https://dl.minio.io/server/minio/release/linux-amd64/ and then provide 

`mc admin update myminio https://myfavorite-mirror.com/minio-server/linux-amd64/minio.sha256sum` 

NOTE: you are choosing the right architecture because we have no way of knowing the top-level directory structure.

**Comment by MAHDTech** [comment] 2020-01-03 02:51
Thanks!

I already have the same directory structure so I will test it out.

**Comment by MAHDTech** [comment] 2020-01-03 13:13
Worked as described for the latest release.

If I wanted to choose a specific release, is there an existing method, I was hoping I could just use the archive URL but it doesn't work as I thought, ie.

```
mc admin update myminio https://myfavorite-mirror.com/minio-server/linux-amd64/archive/minio.RELEASE-XXXXX.sha256sum
```

Seems to be explicitly looking for "minio" named file

https://github.com/minio/minio/blob/dd311623dfe991cb6a0b2fc2c261643eaeb12c10/cmd/update.go#L470

**Comment by harshavardhana** [comment] 2020-01-03 16:49
Yes it is explicitly looking for that, as I said it's not complete @MAHDTech 

Next step was to allow download to all older versions and patch the server.

**Comment by harshavardhana** [comment] 2020-01-03 16:49
Will close this issue, since it's working as expected for now.

**Closed by harshavardhana** 2020-01-03 16:49 UTC
Labels: community, priority: medium, working as intended
