### ISSUE TITLE
Running `mc admin info local --json` immediately after node start gives status only on the current node

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/mc#2279] opened 2017-10-11 08:28 UTC
## Expected behaviour
I have a distributed Minio setup, where I provide all the instances and disks as part of the `server` command. I have a script that is bundled in the entrypoint of the Dockerfile and it does a check if there are errors for the nodes in the cluster using `mc admin info local --json`. The issue is that the `mc admin info local --json` gives output just for the existing node (success and no errors). The script is run even before Minio startup output is printed to the console.

## mc version
Version: 2017-10-10T08:50:07Z
Release-tag: DEVELOPMENT.2017-10-10T08-50-07Z
Commit-id: c10b429dcbeb7071e2758233afeda46d2ed688e5

## minio version
Version: 2017-10-10T08:49:44Z
Release-Tag: DEVELOPMENT.2017-10-10T08-49-44Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21

**Comment by deekoder** [comment] 2017-11-08 00:06
@davidgeorgealex will get back to you. Apologies for the delay.

**Comment by nitisht** [comment] 2017-11-14 08:46
@davidgeorgealex how are you deploying distributed Minio on Docker? Generally in Docker environment, it takes some time for remote server instances to be up and available. Can you add a delay in your script before attempting `mc admin info`

Also, admin API is undergoing a rewrite, you can follow the progress here: https://github.com/minio/mc/pull/2239

**Comment by davidgeorgealex** [comment] 2017-11-15 07:36
@nitisht Thanks for the response. This is exactly what I have did (a timeout). The reason why I open the issue, is the fact that Minio/MC, through `server` command that is run at startup where all the machines and disks are provided, already know that it will be part of a bigger cluster of X machines. So, even if you run the `mc admin info` command right after startup, he can provide this information, with a reasonable status for the machines/disks that are not yet discovered (since remote servers are not yet up/accessible). I was thinking here more on an enhancement that can be done to the API. What do you think?

**Comment by nitisht** [comment] 2017-11-22 09:56
@davidgeorgealex with the new API implementation we'll be following the approach of more real time response. You'll need to wait for the admin API release. We don't have a release date, but it will done soon. 

Meanwhile, if there is nothing else to be addressed here, feel free to close this issue.

**Comment by nitisht** [comment] 2017-11-25 08:45
closing this as working as intended. Feel free to reopen if there are any more issues.

**Closed by nitisht** 2017-11-25 08:45 UTC
Labels: priority: medium
