### ISSUE TITLE
Please add "lowercase" into error message for mb creation

### ISSUE THREAD

**Issue by i4o** [minio/mc#2134] opened 2017-04-19 10:53 UTC
## Expected behaviour

mc mb do/GoProExports
<ERROR> Unable to make bucket ‘do/GoProExports’. Bucket name can contain LOWERCASE alphabet, '-' and numbers, but first character should be an alphabet or number

## Actual behaviour

>mc mb do/GoProExports

<ERROR> Unable to make bucket ‘do/GoProExports’. Bucket name can contain alphabet, '-' and numbers, but first character should be an alphabet or number

When I try this in GUI I get correct error message. Took me a while to find out I have to use lowercase.

**Comment by vadmeste** [comment] 2017-04-19 10:56
@i4o, thanks for reporting. Will do :)

**Comment by badscooter23** [comment] 2017-04-19 16:05
Hang on a second... this does not make complete sense to me (perhaps I am missing something)...

On Minio... with mc... the mb command will force the bucket name to be all lowercase characters, a `-`, or a number

On S3... with aws (cli) ... the mb command allows mixed case

Scotts-MacBook-Pro-2:mc scott$ aws s3 mb s3://scott-GoPro
make_bucket: scott-GoPro

Seems to me that the error is not with the error message but with the routine (isValidBucketName) that is doing the validation... 

I think this is a different bug!

**Comment by badscooter23** [comment] 2017-04-19 16:44
Bottom line, this bug will actually show up in multiple commands - any mc command that takes a bucket name in the path... 

It's not just an error message problem with `mc mb`

**Comment by badscooter23** [comment] 2017-04-19 16:46
Further example:

`mc mb GoPro` 

will succeed in creating a "bucket" (which is really a directory) in the local file system. The problem is with the routine that is attempting to validate the bucket name in the `cmd/client-s3.go`

**Comment by badscooter23** [comment] 2017-04-19 16:52
Here is the problem... 
The minio code is refers to this Amazon S3 documentation
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

which in turn points at this page
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

The second page states:

- Bucketnames must be at least 3 and no more than 63 characters long.

- Bucket names must be a series of one or more labels. Adjacent labels are separated by a single period (.). Bucket names can contain lowercase letters, numbers, and hyphens. Each label must start and end with a lowercase letter or a number.

- Bucket names must not be formatted as an IP address (e.g., 192.168.5.4).

- When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic. We recommend that you do not use periods (".") in bucket names.

The minio code attempts to implement these restrictions, but clearly the Amazon S3 CLI does not follow these rules (and bucket names with mixed case are allowed on S3).

**Comment by badscooter23** [comment] 2017-04-19 16:57
`mc` is using the following regular expression to validate the bucket name:

var validBucketName = regexp.MustCompile(`^[a-z0-9][a-z0-9\.\-]{1,61}[a-z0-9]$`)

This is more restrictive and Amazon (even though it attempts to match the documentation).

**Comment by vadmeste** [comment] 2017-04-19 17:03
I confirm this works:

`aws s3 mb s3://Vadmeste`

But Minio (for Windows) won't support this.

But anyway, it looks okay for me to remove this restriction.

**Comment by badscooter23** [comment] 2017-04-19 17:27
It's easy to change to allow mixed case... 
My concern is that AWS's behavior does not match their documentation, so that creates a bit of a dilemma ...

- Should `mc` be compatible with the S3 documentation (not allowing mixed case)?
- Should `mc` be compatible with the S3 behavior (allowing mixed case)? 
- Should the `mc` behavior be configurable?

I think this need a little more discussion before we change it. I could see some merit in having a config parm (maybe something like `allow_mixed_case=True|False`... the default could be False to match the docmentation, but the user could set to true (which would match S3 behavior).

Also we should check to see what Google does... I haven't done that yet. Amazon S3 behavior would be the `bible` for minio mc to follow, but Google is relevant and I would not be surprised at all if different S3 providers do different things. (not just for this particular issue, but in general). 

If there are multiple compatibility quirks across providers that would make a stronger case for configuration parms to define minio mc behavior.

**Comment by badscooter23** [comment] 2017-04-19 17:38
It's not as simple as just changing the validation string in `mc` (I already tried that)... I think there is a similar validation string in `minio server` because you still get an error... 

Scotts-MacBook-Pro-2:test scott$ mc mb myminio/GoPro
mc: <ERROR> Unable to make bucket `myminio/GoPro`. Bucket name contains invalid characters.
Scotts-MacBook-Pro-2:test scott$ mc mb myminio/GoPro --debug
mc: <ERROR> Unable to make bucket `myminio/GoPro`. Bucket name contains invalid characters.
 (1) mb-main.go:126 cmd.mainMakeBucket(..) Tags: [myminio/GoPro]
 (0) client-s3.go:765 cmd.(*s3Client).MakeBucket(..)
 Release-Tag:DEVELOPMENT.2017-04-19T17-30-55Z | Commit:9a881562b93f | Host:Scotts-MacBook-Pro-2.local | OS:darwin | Arch:amd64 | Lang:go1.7.5 | Mem:1.0MB/2.8MB | Heap:1.0MB/1.6MB

**Comment by vadmeste** [comment] 2017-04-19 17:57
> . I think there is a similar validation string in minio server

Yes there is. And we also need it because Minio supports Windows which is not case sensitive. We cannot create both 'bucket' and 'Bucket' at the same time.

**Comment by badscooter23** [comment] 2017-04-19 18:01
This is a bigger problem/dilemma for Minio... 

The legal syntax for a bucket and/or object depends on context, specifically it depends on the backend. 

The rules for "legal" for a 'filesystem' are different than an 'object store'.
The rules for 'filesystems' themselves depend on the underlying FS and OS.
The rules for an 'object store' likely vary subtly from vendor to vendor (eg: Google may not match S3 perfectly) - not verified.

In my test env, the minio server is backed by a Linux FS (which would allow mixed case and is case sensitive). In your case your local minio server is backed by a Windows FS which folds case so `Bucket` = `bucket`. 

This is what makes this a little tricky.

**Comment by badscooter23** [comment] 2017-04-19 18:02
I think it is pretty restrictive (IMO) to disallow mixed case when the backend is really S3 when S3 actually allows mixed case (despite what the documentation says).

**Comment by donatello** [comment] 2017-04-19 18:05
S3 allows mixed case only in one region - us-east-1 - all other regions have the same restrictions - https://stackoverflow.com/questions/18715970/amazon-s3-bucket-naming-convention

**Comment by harshavardhana** [comment] 2017-04-19 18:11
> I think it is pretty restrictive (IMO) to disallow mixed case when the backend is really S3 when S3 actually allows mixed case (despite what the documentation says).

For S3 it is better to not provide a way to create bucket names with capital letters. It is noted that this feature will be removed in future on `us-east-1`. 

On Minio server we only allow lower case bucket names to coincide with S3 behavior. From `mc` point of view it is a simple change. Change the error message to appropriately indicate that only lowercase characters are allowed.

**Comment by badscooter23** [comment] 2017-04-19 18:43
This is a VERY helpful clarification... if the behavior is `us-east-1` specific I agree it does not make sense to allow it for just one region (especially if they are going to change it in the future).

**Comment by badscooter23** [comment] 2017-04-19 19:02
Ok... done! 

Scotts-MacBook-Pro-2:mc scott$ mc mb myminio/GoPro
mc: <ERROR> Unable to make bucket `myminio/GoPro`. Bucket names can contain lowercase alpha characters `a-z`, numbers '0-9', and '-'. First character cannot be a '-'

**Comment by harshavardhana** [comment] 2017-04-19 19:30
> I probably makes sense to document this somewhere - at least IMO.

S3 actually documented this here http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

```While the US East (N. Virginia) region currently allows non-compliant DNS bucket naming, we are moving to the same DNS-compliant bucket naming convention for the US East (N. Virginia) region in the coming months```

**Comment by badscooter23** [comment] 2017-04-19 21:57
My point was that it should probably be documented in a Minio doc... If nothing else with a pointer from the `Minio Client Complete Guid` to the AWS doc you reference.

**Comment by vadmeste** [comment] 2017-04-22 21:16
Fixed by #2135

**Closed by vadmeste** 2017-04-22 21:16 UTC
Labels: community, priority: medium
