### ISSUE TITLE
Invalid result for mc rb

### ISSUE THREAD

**Issue by i0x71** [minio/mc#3486] opened 2020-11-11 20:27 UTC
Looks like "Removed ...... successfully" is being printed erroneously in this case, as its not actually being removed.

root@sandbox:~# mc rb dot9/electronics
mc: <ERROR> Failed to remove `dot9/electronics`, continuing.. The bucket you tried to delete is not empty
**Removed `dot9/electronics` successfully.**

root@sandbox:~# mc ls dot9/electronics      
[2020-11-11 20:24:48 UTC]     0B esp32/

It also looks like mc mv does not remove directories or prefixes, is this intended behaviour as well ?
mc version RELEASE.2020-10-03T02-54-56Z
minio    Version: 2020-11-10T21:02:24Z

**Comment by i0x71** [comment] 2020-11-12 18:40
Adding to that, It looks like there is no way to forcefully remove a bucket when there is an empty folder inside.

root@sandbox:~# mc rb --force --dangerous dot9/electronics
mc: <ERROR> Failed to remove `dot9/electronics`, continuing.. The bucket you tried to delete is not empty
Removed `dot9/electronics` successfully.
root@sandbox:~# mc ls dot9/electronics
[2020-11-12 18:38:29 UTC]     0B esp32/

**Comment by i0x71** [comment] 2020-11-12 18:48
Guys, looks like this is another bug, rm and rb fail remove empty directory, rm complains that directory doesnt exist, which ls says otherwise.
root@sandbox:~# mc rb dot9/electronics/esp32
mc: <ERROR> Failed to remove `dot9/electronics/esp32`, continuing.. **cannot delete prefixes with `mc rb` command - Use`mc rm` instead**
Removed `dot9/electronics/esp32` successfully.

root@sandbox:~# mc rm -r --force dot9/electronics/esp32
mc: <ERROR> Failed to remove `dot9/electronics/esp32`. Object does not exist
root@sandbox:~# mc ls dot9/electronics
[2020-11-12 18:44:16 UTC]     0B esp32/
root@sandbox:~# mc rm -r --force dot9/electronics/esp32/
mc: <ERROR> Failed to remove `dot9/electronics/esp32/`. Object does not exist
root@sandbox:~# mc ls dot9/electronics
[2020-11-12 18:46:52 UTC]     0B esp32/

**Comment by kannappanr** [comment] 2020-12-01 23:47
@i0x71 `mc rb` needs `--force` flag to delete objects and buckets. It will also not remove just prefixes and objects.

```
 $ mc ls play/test
[2020-12-01 15:42:36 PST]     0B prefix/
$ mc rm -r --force play/test/prefix/
mc: <ERROR> Failed to remove `play/test/prefix/`. Object does not exist
$ mc rm play/test/prefix/
Removing `play/test/prefix/`.
```
The `mc rm -r --force` for an empty prefix is a bug. Will fix that.

**Comment by ebozduman** [comment] 2020-12-17 19:11
@i0x71 

There are some changes/fixes made into `mc` since the version you were using. I see some of the issues you pointed out are already resolved in the build, I made from the top of the mc master branch.

Could you check and run your tests/commands one more time and let us know if you see any issues with an mc build made from the top of the master branch?
 I appreciate your updated input while I look into the issue @kannappanr described above.

**Comment by ebozduman** [comment] 2021-02-04 08:24
There is nothing to address in this issues.
Please check the latest `mc` build.
The removal of empty prefix we talked about is also deemed to be `not an issue` by the team. You can remove an empty prefix by specifying the prefix path without a slash, `/`, at the end.
So, closing it as `working as intended`.

**Closed by ebozduman** 2021-02-04 08:24 UTC
Labels: community, working as intended
