### ISSUE TITLE
arm64: panic: notify: epoll_wait(2) error function not implemented

### ISSUE THREAD

**Issue by larmog** [minio/mc#2047] opened 2017-02-28 05:25 UTC
## Expected behaviour
No panic when running `mc mirror`

## Actual behaviour
`mc` terminates immediately

## Steps to reproduce the behaviour

```
$ mc mirror -w mirror myminio/dbstore

panic: notify: epoll_wait(2) error function not implemented

goroutine 11 [running]:
panic(0x452de0, 0x44201fa290)
	/home/builder/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x390
github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*inotify).loop(0x44200f8000, 0x4420017920)
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/watcher_inotify.go:215 +0x568
created by github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/builder/mygo/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/watcher_inotify.go:133 +0x210
```

## mc version

```
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01
```

## System information
Ubuntu 16.04LTS on Odroid C2
```
Linux minion0 3.14.79-106 #1 SMP PREEMPT Thu Feb 23 07:05:09 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by harshavardhana** [comment] 2017-02-28 06:56
The problem is the ARM kernel lacks a syscall but we did indeed have a fix for this - https://github.com/golang/sys/commit/324e137  and our vendor library should have this fix. 

Let me check again.

**Comment by harshavardhana** [comment] 2017-02-28 07:24
Looks like the bug is upstream sending a fix upstream. https://github.com/rjeczalik/notify/pull/116

**Comment by larmog** [comment] 2017-02-28 18:47
ok, great

**Closed** 2017-03-01 23:16 UTC
Labels: bug
