### ISSUE TITLE
Server expects client requests with 'admin' API version 'v2', found 'v1'

### ISSUE THREAD

**Issue by rmundel** [minio/mc#2960] opened 2019-11-18 03:38 UTC
## Expected behavior
One should be able to manage the server.

## Actual behavior
mc: <ERROR> Cannot get service status. Server expects client requests with 'admin' API version 'v2', found 'v1', please upgrade the client to latest releases.

## Steps to reproduce the behavior
Installed using the script bellow
[minio.txt](https://github.com/minio/mc/files/3856694/minio.txt)

## mc version
mc version RELEASE.2019-10-09T22-54-57Z

## minio version
Release-Tag: RELEASE.2019-10-12T01-39-57Z

## System information
VM running Ubuntu 18.04.2 LTS with 4 CORES and 4GB RAM with a 40GB disk

**Comment by harshavardhana** [comment] 2019-11-18 04:08
We haven't released a version with v2 , if you are compiling through source please use master branches instead.

**Comment by rmundel** [comment] 2019-11-18 04:25
Strange, because here's what I'm doing:

# get & install minio binary
curl -s -O https://dl.minio.io/server/minio/release/linux-amd64/minio
sudo mv minio /usr/local/bin
sudo chmod +x /usr/local/bin/minio
sudo chown minio-user:minio-user /usr/local/bin/minio

# get & install mc binary
wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
sudo mv mc /usr/local/bin
sudo chmod +x /usr/local/bin/mc

**Comment by harshavardhana** [comment] 2019-11-18 04:33
I am pretty sure that is something here, you have locally two versions of the binary running somewhere which is coming in the way. Here the culprit is server and your server seems to be from the master branch.

**Comment by tiyberius** [comment] 2019-11-28 02:45
For what it's worth, I am having this same problem. I installed Minio server using Docker as per the instructions on https://min.io/download#/linux like so

docker run -p 9000:9000 -v /mnt/data:/data minio/minio server /data

And installed the client using

wget https://dl.min.io/client/mc/release/linux-amd64/mc
chmod +x mc
./mc --help

And I'm getting the same error message as @rmundel

**Comment by harshavardhana** [comment] 2019-11-28 03:16
I have no idea how you can reproduce this latest released version is v1, mc uses v1 here are the results

```
~ docker run --rm -p 9000:9000 -v /tmp/data:/data -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 minio/minio server /data
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000      

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000      

```

```
~ ./mc.release config host add myminio http://localhost:9000 minio minio123
Added `myminio` successfully.
~ ./mc.release admin info server myminio
●  localhost:9000
   Uptime: 49 seconds 
  Version: 2019-10-12T01:39:57Z
  Storage: Used 31 GiB, Free 13 GiB

~ ./mc.release admin info server myminio --debug |grep admin/v1
mc.release: <DEBUG> GET /minio/admin/v1/info HTTP/1.1
```

```
~ docker run --rm minio/minio version
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

```
~ ./mc.release version
Version: 2019-10-09T22:54:57Z
Release-tag: RELEASE.2019-10-09T22-54-57Z
Commit-id: f93fe1330a3647b1afaff0ed8c188d2897bf391e
```

I am going to close this issue, since this looks like an environment issue at your end. Please version the version posted here and let me know if they match. If they don't fix it. 

```

**Closed by harshavardhana** 2019-11-28 03:16 UTC

**Comment by JorisJamers** [comment] 2019-11-29 12:50
We have encountered the same issue, while installing MinIO via the Helm chart. Looks like there is a new version of Minio running inside of the helm chart. 

Your version is RELEASE.2019-10-12T01-39-57Z while the chart is running the following version: 
  2019-11-28T00:17:36Z

```
/ # minio
NAME:
  minio - High Performance Object Storage

DESCRIPTION:
  Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   start object storage server
  gateway  start object storage gateway

FLAGS:
  --config-dir value, -C value  [DEPRECATED] path to legacy configuration directory (default: "/root/.minio")
  --certs-dir value, -S value   path to certs directory (default: "/root/.minio/certs")
  --quiet                       disable startup information
  --anonymous                   hide sensitive information from logging
  --json                        output server logs and startup information in json format
  --compat                      enable strict S3 compatibility by turning off certain performance optimizations
  --help, -h                    show help

VERSION:
  2019-11-28T00:17:36Z
```

**Comment by nitisht** [comment] 2019-11-29 13:31
@JorisJamers we're yet to make the release, but the helm chart uses code from latest master, so you're seeing this issue. 

For now, please start the helm chart with flag `image.tag=RELEASE.2019-10-12T01-39-57Z` and then mc should work fine

**Comment by JorisJamers** [comment] 2019-11-29 14:01
> @JorisJamers we're yet to make the release, but the helm chart uses code from latest master, so you're seeing this issue.
> 
> For now, please start the helm chart with flag `image.tag=RELEASE.2019-10-12T01-39-57Z` and then mc should work fine

Hi @nitisht we tried to start the helm chart with the following command : 
```
helm install --set image.tag=RELEASE.2019-10-12T01-39-57Z,persistence.existingClaim=minio,environment.MINIO_SSE_AUTO_ENCRYPTION=on,environment.MINIO_SSE_MASTER_KEY=my-minio-key:<keyvalue>--name minio stable/minio --namespace kube-storage
```

But the pod will go into a **CrashLoopBackoff** with the following logs 
```
k logs minio-598b6865c-wbp98 -n kube-storage
^[[AERROR Unable to initialize config system: invalid character '¿' looking for beginning of value
```

Is there something wrong with the startup command?

**Comment by nitisht** [comment] 2019-11-29 14:10
You'll need to clean up the `.minio.sys` data directories on the PVs before starting MinIO

**Comment by rmundel** [comment] 2019-11-29 14:22
So, I reinstalled with the same steps as before in a brand new Ubuntu 18.04 server and the results are the same:

minio --version
2019-10-12T01:39:57Z

mc -v
RELEASE.2019-10-09T22-54-57Z

mc admin info server play
mc: <ERROR> Cannot get service status. Server expects client requests with 'admin' API version 'v2', found 'v1', please upgrade the client to latest releases.

**Comment by nitisht** [comment] 2019-11-29 14:40
> mc admin info server play

Why would you install MinIO locally and point it to `play` server? Can you try pointing it to your local MinIO server?

**Comment by JorisJamers** [comment] 2019-11-29 14:45
> You'll need to clean up the `.minio.sys` data directories on the PVs before starting MinIO

This worked! Thanks for the help, was really usefull! Maybe a solution for @rmundel as well.

**Comment by rmundel** [comment] 2019-11-29 14:56
Dang, I was completely misled about the problem.
As @nitisht pointed, I was trying to connect to play server instead of my local server.
Sorry guys.
Thanks!
