### ISSUE TITLE
resuming mc cp session seems to go slower (and use less parallelism) than original cp

### ISSUE THREAD

**Issue by varung** [minio/mc#2259] opened 2017-09-24 12:08 UTC
I initiated an mc cp --recursive
copying goes at 50mb/s, and top reveals many mc processes. Great!
copy failed due to server 504
mc session resume {ID}

copy now goes slow (like 7mb/s, and top/ps reveals only one mc session resume process)
This seems surprising.

**Comment by harshavardhana** [comment] 2017-09-26 07:19
`mc cp` doesn't upload in parallel, i am not sure what you are implying. Also i am not able to reproduce this on my end. Can you provide us more details? like `mc` version, operating system etc.

**Comment by harshavardhana** [comment] 2017-09-28 18:59
> mc cp doesn't upload in parallel, i am not sure what you are implying. Also i am not able to reproduce this on my end. Can you provide us more details? like mc version, operating system etc.

@varung checking back to see if you saw our previous comment?

**Comment by varung** [comment] 2017-09-28 19:02
Hi

I thought that when you use -r, mc cp *would* upload in parallel. I
certainly saw multiple processes, but maybe I was imagining that?

If it doesn't, I would really like it if it did. So I don't have to wrap it
in some find | xargs -P stuff. Or just use the go library myself.

Finally, having to manually re-resume sessions is a really annoying. Would
be nice if somehow that could be avoided. My goal when I do mc cp -r is
just to get my directory into s3 as fast and reliably as possible.

**Comment by varung** [comment] 2017-09-28 19:03
-r being recursive upload.

**Comment by harshavardhana** [comment] 2017-09-28 19:39
@varung we have a PR which will make things parallel but currently its not .. https://github.com/minio/mc/pull/2258

**Comment by harshavardhana** [comment] 2017-10-11 09:09
@varung can you test the latest master and let us know if it addresses your issue? #2258 is merged.

**Comment by harshavardhana** [comment] 2017-10-31 01:29
Closing this as fixed in master and released.

**Closed by harshavardhana** 2017-10-31 01:29 UTC
Labels: priority: medium, triage
