### ISSUE TITLE
Can't use `mc cp` to upload files.

### ISSUE THREAD

**Issue by aybabtme** [minio/mc#2490] opened 2018-07-24 15:01 UTC
## Expected behaviour

I should be able to `mc cp filename bucket/filename`.

## Actual behaviour

The tool seems to have problems reading files:

```bash
# mc cp lol.txt myalias/testing
mc: <ERROR> Failed to copy `lol.txt`. Input reader closed pre-maturely. Expected `12` bytes, but only received `0` bytes.
mc: <ERROR> Session safely terminated. To resume session `mc session resume iqIDvbKK`
```
and equivalent:
```
# cat lol.txt | mc pipe myalias/testing/lol.txt
mc: <ERROR> Unable to write to one or more targets. Input reader closed pre-maturely. Expected `-1` bytes, but only received `0` bytes.
```

## Steps to reproduce the behaviour

See above.

## mc version

```
# mc version
Version: 2018-07-13T00:53:22Z
Release-tag: RELEASE.2018-07-13T00-53-22Z
Commit-id: 70dcf20d747d305f73a117b4787acf46e6809d99
```

## System information

```
# uname -a
Linux myhostname 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux
```

**Comment by kannappanr** [comment] 2018-07-24 18:16
@aybabtme thanks for filing this issue. Is there anything special with this file, because we normally do not see this issue.  Can you also run the same set of commands with a `--debug` option and paste the output here.

Also, what is the output of `cat lol.txt` ? Are you able to see the contents of the file.

**Comment by aybabtme** [comment] 2018-07-25 11:09
hi @kannappanr 

The content of `lol.txt` is:
```
$ cat lol.txt
lololololol
```

The command with debug output is:
```
$ mc cp --debug lol.txt somerandombucketname/testing/
mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T110627Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:06:27 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:06:22 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx0000000000000000792db-005b5859b2-a9db55-nyc3a

mc: <DEBUG> Response Time:  1.130554534s

mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T110628Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:06:27 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:06:22 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx0000000000000000c4e6b-005b5859b3-aaa7d0-nyc3a

mc: <DEBUG> Response Time:  106.894894ms

mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T110628Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:06:27 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:06:22 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx00000000000000008ebd7-005b5859b3-aaac9e-nyc3a

mc: <DEBUG> Response Time:  106.792281ms

 0 B / 12 B ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   0.00%mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T110629Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:06:27 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:06:22 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx000000000000000087e5d-005b5859b3-a9d907-nyc3a

mc: <DEBUG> Response Time:  100.784288ms

mc: <ERROR> Failed to copy `lol.txt`. Input reader closed pre-maturely. Expected `12` bytes, but only received `0` bytes.
 (3) cp-main.go:404 cmd.doCopySession(..) Tags: [lol.txt]
 (2) common-methods.go:196 cmd.uploadSourceToTargetURL(..) Tags: [https://somerandombucketname.nyc3.digitaloceanspaces.com/testing/lol.txt]
 (1) common-methods.go:130 cmd.putTargetStream(..) Tags: [somerandombucketname, https://somerandombucketname.nyc3.digitaloceanspaces.com/testing/lol.txt]
 (0) client-s3.go:650 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2018-07-13T00-53-22Z | Commit:70dcf20d747d | Host:orion-on-linux | OS:linux | Arch:amd64 | Lang:go1.10.2 | Mem:4.7MB/13MB | Heap:4.7MB/8.7MB
mc: <ERROR> Session safely terminated. To resume session `mc session resume iWkeZnJm`
```

**Comment by aybabtme** [comment] 2018-07-25 11:36
The same happens if I run it directly on macOS (not in Docker):
```
$ uname -a
Darwin orion 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
$ mc version
Version: 2018-07-13T00:53:22Z
Release-tag: RELEASE.2018-07-13T00-53-22Z
Commit-id: 70dcf20d747d305f73a117b4787acf46e6809d99
```

Reproducer:
```
$ echo lololololol > /tmp/lol.txt
$ mc cp /tmp/lol.txt somerandombucketname/testing
mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T113456Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:34:56 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:18:58 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx000000000000000107b60-005b586060-aaa7d0-nyc3a

mc: <DEBUG> Response Time:  566.832185ms

mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T113456Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:34:56 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:18:58 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx0000000000000000caea2-005b586060-a9d907-nyc3a

mc: <DEBUG> Response Time:  101.066669ms

mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T113456Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:34:56 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:18:58 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx0000000000000000caeb1-005b586060-a9d907-nyc3a

mc: <DEBUG> Response Time:  102.057872ms

mc: <DEBUG> GET /testing/?location= HTTP/1.1
Host: somerandombucketname.nyc3.digitaloceanspaces.com
User-Agent: Minio (darwin; amd64) minio-go/v6.0.6 mc/2018-07-13T00:53:22Z
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180725T113457Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: binary/octet-stream
Date: Wed, 25 Jul 2018 11:34:57 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Last-Modified: Wed, 25 Jul 2018 11:18:58 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Amz-Request-Id: tx0000000000000000cc776-005b586061-aaac9e-nyc3a

mc: <DEBUG> Response Time:  100.742877ms

mc: <ERROR> Failed to copy `/tmp/lol.txt`. Input reader closed pre-maturely. Expected `12` bytes, but only received `0` bytes.
 (3) cp-main.go:404 cmd.doCopySession(..) Tags: [/tmp/lol.txt]
 (2) common-methods.go:196 cmd.uploadSourceToTargetURL(..) Tags: [https://somerandombucketname.nyc3.digitaloceanspaces.com/testing/lol.txt]
 (1) common-methods.go:130 cmd.putTargetStream(..) Tags: [nyc3-agent-releases, https://somerandombucketname.nyc3.digitaloceanspaces.com/testing/lol.txt]
 (0) client-s3.go:650 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2018-07-13T00-53-22Z | Commit:70dcf20d747d | Host:orion | OS:darwin | Arch:amd64 | Lang:go1.10.2 | Mem:4.0MB/11MB | Heap:4.0MB/6.4MB
mc: <ERROR> Session safely terminated. To resume session `mc session resume JKPqUhlD`
```

**Comment by eco-minio** [comment] 2018-07-25 23:14
@aybabtme

As you mentioned you used  `mc config host add somerandombucketname https://somerandombucketname.nyc3.digitaloceanspaces.com/ $ACCESS_KEY $SECRET_KEY --api S3v4`

You should remove that alias and re-add something like this
```mc config host add myalias http://nyc3.digitaloceanspaces.com <key> <secret> --lookup "dns"```

**Comment by eco-minio** [comment] 2018-08-23 18:53
We are not able to reproduce this issue, it appears to be with your specific environment.  Let us know if you are still experiencing using the updated mc command provided against the latest build.

**Comment by deekoder** [comment] 2018-08-29 19:01
@aybabtme since we are not able to repro this at our end, I will go ahead and close this. Please reopen to continue this conversation if you feel it is still not fixed. Also please feel free to come say hi to us at slack.minio.io.

**Closed by deekoder** 2018-08-29 19:01 UTC
Labels: community, priority: medium, triage, working as intended
