### ISSUE TITLE
mc reports "Removed <bucket> successfully" although it didn't

### ISSUE THREAD

**Issue by mrdsam** [minio/mc#3595] opened 2021-02-04 13:03 UTC
## Expected behavior
mc should return a message like "Failed to remove bucket <bucket>"

## Actual behavior
mc says "Removed `s3/<bucket>` successfully."  This is not true.

## Steps to reproduce the behavior
1) Create a user 'bucketadmin' which is member of this two policies:

**a) Policy global-bucketadmin**
`
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketNotification",
    "s3:GetBucketVersioning",
    "s3:ListBucket",
    "s3:PutBucketPolicy",
    "s3:CreateBucket",
    "s3:DeleteBucketPolicy",
    "s3:GetBucketLocation",
    "s3:GetBucketObjectLockConfiguration",
    "s3:GetBucketTagging",
    "s3:PutBucketNotification",
    "s3:PutBucketVersioning",
    "s3:DeleteBucket",
    "s3:PutBucketObjectLockConfiguration",
    "s3:ListBucketVersions",
    "s3:ListAllMyBuckets",
    "s3:ListBucketMultipartUploads",
    "s3:PutBucketTagging",
    "s3:GetBucketPolicy"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
`
**b) Policy global-useradmin**
`
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:ServerInfo",
    "admin:DeleteUser",
    "admin:CreateUser",
    "admin:DataUsageInfo",
    "admin:EnableUser",
    "admin:RemoveUserFromGroup",
    "admin:ServerTrace",
    "admin:TopLocksInfo",
    "admin:ConsoleLog",
    "admin:DisableUser",
    "admin:GetPolicy",
    "admin:ListGroups",
    "admin:ListUserPolicies",
    "admin:SetBucketQuota",
    "admin:StorageInfo",
    "admin:AddUserToGroup",
    "admin:GetGroup",
    "admin:GetUser",
    "admin:ListUsers",
    "admin:OBDInfo",
    "admin:GetBucketQuota"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  }
 ]
}
`

2) As master admin user, create a bucket and upload some files / directories

3) As 'bucketadmin', try to remove the bucket created in step 2. This
will fail, as intended, but mc will claim it removed the bucket
successfully.

`mc rb --force s3/<bucket>`

mc: <ERROR> Failed to remove `s3/<bucket>`, continuing.. Access Denied.
mc: <ERROR> Failed to remove `s3/<bucket>`, continuing.. Access Denied.
[ ... one line for each object in bucket ... ]
mc: <ERROR> Failed to remove `s3/<bucket>`, continuing.. Access Denied.
mc: <ERROR> Failed to remove `s3/<bucket>`, continuing.. Access Denied.
Removed `s3/<bucket>` successfully. 

## mc --version
- mc version RELEASE.2021-01-30T00-50-42Z

## System information
Server: FreeBSD 12.1, Client: Linux Ubnutu

**Comment by ebozduman** [comment] 2021-03-04 12:19
@mrdsam,

This is duplicate of issue #3387.

The fix for it, PR#3616, is ready and it's review is almost done.

It'll be available in the next mc release and address your issue.

The fix will change the existing behavior by stopping at the first error as soon as it is hit, and either error out or show the success message.

So, closing the issue as a duplicate of issue ##3387.

**Closed by ebozduman** 2021-03-04 12:19 UTC
Labels: community, duplicate
