### ISSUE TITLE
mc never returns when minio server returns `XMinioStorageFull`

### ISSUE THREAD

**Issue by balamurugana** [minio/mc#2392] opened 2018-02-15 07:41 UTC
## Expected behaviour
Error out after some retries

## Actual behaviour
Never returns

## Steps to reproduce the behaviour
Have minio server running with < 1GB free space.

## mc version
Version: 2018-02-15T07:35:19Z
Release-tag: DEVELOPMENT.2018-02-15T07-35-19Z
Commit-id: 335a53ad2911cd854255a18a6be3ed3c738c30c9

**Comment by poornas** [comment] 2018-02-16 21:44
@balamurugana , tried to simulate this issue by running minio server in fs as well as xl mode after decreasing the percentage of available free disk space- mc does return after retrying with 
fs
```
 mc: <ERROR> Failed to copy `/home/kris/Downloads/large105M.txt`. Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.
```
xl 
```
mc: <ERROR> Failed to copy `/home/kris/Downloads/large105M.txt`. Multiple disks failures, unable to write data.
```
Was the issue reproducible consistently on your system? Could you share more details of what operation you were attempting in mc and server mode

**Comment by balamurugana** [comment] 2018-02-18 01:25
When did you get the error? After > 10mins? What minio version you used? Note that I was found in `mc` master

**Comment by poornas** [comment] 2018-02-18 17:43
No @balamurugana , the error message was displayed in less than 2 mins. I used minio master and mc master.

**Comment by balamurugana** [comment] 2018-02-20 05:44
I was using large bucket support in minio server.  Probably you would need to check with large bucket support.

**Comment by poornas** [comment] 2018-02-20 18:12
thanks @balamurugana

**Comment by poornas** [comment] 2018-02-20 22:09
@balamurugana, tried replicating the error you saw with large bucket support. Reduced the usable disk space to 20% of disk capacity and copied 10GB files until I ran out of space. mc terminates the operation with Multiple disks failure - don't see the XMinioStorage
```
minio server /tmp/b2/backend{1...128}
➜  bs for i in {1..10}; do mc cp ~/Downloads/large10G.txt myminio/bucket/$i ;done
 0 B / 10.00 GB ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   0.00%
.../large10G.txt:  657.00 MB / 10.00 GB ┃▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   6.42% 9.50 MB/s 16m44s
 (0) client-s3.go:630 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:kris-ThinkPad-X1-Carbon-5th | OS:linux | Arch:amd64 | Lang:go1.9.4 | Mem:4.2MB/13MB | Heap:4.2MB/8.8MB
mc: <ERROR> Failed to copy `/home/kris/Downloads/large10G.txt`. Multiple disks failures, unable to write data.
mc: <ERROR> Session safely terminated. To resume session `mc session resume ScjFELIT`

```

**Comment by harshavardhana** [comment] 2018-02-20 23:44
> mc: <ERROR> Failed to copy `/home/kris/Downloads/large10G.txt`. Multiple disks failures, unable to write data.

This is expected since quorum would have failed

**Comment by harshavardhana** [comment] 2018-02-27 17:17
Can we close this issue as not reproducible ?

**Comment by deekoder** [comment] 2018-02-28 22:53
yes. Bala i think this is no longer reproducing. Closing it hence.

**Closed by deekoder** 2018-02-28 22:53 UTC
Labels: priority: medium, working as intended
