### ISSUE TITLE
MC should not modify my .zshrc without special permission

### ISSUE THREAD

**Issue by vooon** [minio/mc#2750] opened 2019-04-17 06:30 UTC
## Expected behavior
Program asks to install or not completion.
And if it is allowed to install, it should use correct binary name.
Because this mc conflicts with Midnight Commander i renamed binary to `minio-mc`, but completion is set for `mc`.

## Actual behavior
Program writes to shell rc file without any approval.
Always uses `mc` name for completion.

## Steps to reproduce the behavior
Run any mc command, e.g. `mc version`.

## mc version
Version: 2019-04-15T17:01:49Z
Release-tag: DEVELOPMENT.2019-04-15T17-01-49Z
Commit-id: 5729a01e691cc05142bcb257163e887062dbecd3

## System information
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

**Comment by harshavardhana** [comment] 2019-04-17 16:19
Duplicate of #2722

**Comment by kannappanr** [comment] 2019-05-09 20:53
@vooon Closing this issue as duplicate of #2722 . The status can be tracked in issue #2722 . Please feel free to reach out to us if you have further questions.

**Closed by kannappanr** 2019-05-09 20:53 UTC
Labels: community, priority: medium, triage
