### ISSUE TITLE
error listing bucket 

### ISSUE THREAD

**Issue by kotarusv** [minio/mc#3093] opened 2020-02-25 21:46 UTC
## Expected behavior
mc command should list the objects in bucket

## Actual behavior
getting mc: <ERROR> Unable to list folder. Truncated response should have continuation token set error 

## Steps to reproduce the behavior
# mc ls prd-rtp/rtp-registry/
mc: <ERROR> Unable to list folder. Truncated response should have continuation token set
-> Using Ceph bucket

## mc --version
- (paste output of `mc --version`)

# mc --version
mc version RELEASE.2020-02-25T18-10-03Z

## System information
# cat /etc/*release*
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)
cpe:/o:redhat:enterprise_linux:7.6:ga:server

**Comment by kotarusv** [comment] 2020-02-25 21:49
any command is giving the same error. is anything to do with bucker size?

mc du prd-rtp/rtp-registry/
mc: <ERROR> Failed to find disk usage of `prd-rtp/rtp-registry/` recursively. Truncated response should have continuation token set

**Comment by kannappanr** [comment] 2020-02-25 23:43
@kotarusv This is an issue with `ceph` Please take a look at https://github.com/minio/minio-go/issues/1130 . https://github.com/minio/mc/issues/3067 for more details

**Comment by harshavardhana** [comment] 2020-02-26 01:16
Closing as duplicate of #3067

**Closed by harshavardhana** 2020-02-26 01:16 UTC
