### ISSUE TITLE
mc mirror from s3 to distributed minio causes duplicate folders

### ISSUE THREAD

**Issue by sstubbs** [minio/mc#3534] opened 2020-12-15 21:45 UTC
## Expected behavior
`mc mirror` and `mc cp --recursive` to produce similar results when copying s3 bucket to an empty Minio bucket

## Actual behavior
After using mc mirror and trying to open that bucket in the web UI it freezes when listing the objects of the bucket. When looking at the filesystem I see `mc mirror` creates  `__XLDIR__` folders whereas `mc cp` does not.  

## Steps to reproduce the behavior
I'm not sure if this is a bug or  something I am doing wrong. When I run `mc cp --recursive s3/bucketname/ minio/bucketname/` everything copies as expected. However if I use `mc mirror s3/bucketname/ minio/bucketname/` I have a problem.

## mc --version
`RELEASE.2020-11-17T00-39-14Z`

## System information
I've tried `mc` on `Ubuntu 20.04` and `PopOS 20.10` desktop and have the same issue.
Server running Minio is a LXD container with minio in distributed mode using 4 drives. Host OS is `Ubuntu 20.04 server` and the container is running the same OS.

**Comment by ebozduman** [comment] 2021-02-24 09:55
@sstubbs,

I cannot reproduce the issue with the latest mc version you've used, and neither with the current release or the one from the top of the branch.

I need more information on how to reproduce the problem.
Several things I'd like you to do to help me understand the problem better:
- what is the exact mc command you use?
- Could you try to mirror a different bucket from s3 to a different minio bucket and still see the issue?
- If possible, could you try reproducing the issue after starting minio server without LXD container, maybe locally (using port numbers) or docker?
- Could you explain how minio service is started, the exact commands, scripts and any other specific information about the setup? Any extra information might 
 be helpful.
- Could you also try with the latest released mc, if you can?

**Comment by ebozduman** [comment] 2021-03-05 02:34
@sstubbs,

If we don't hear from you, we'll assume you do not see this issue anymore.
Please let us know if you can still reproduce it.

**Comment by harshavardhana** [comment] 2021-03-05 07:16
> @sstubbs,
> 
> If we don't hear from you, we'll assume you do not see this issue anymore.
> Please let us know if you can still reproduce it.

Closing let's reopen if seen again..

**Closed by harshavardhana** 2021-03-05 07:16 UTC
Labels: community, triage

**Comment by v60fan** [comment] 2023-08-18 12:32
I can reproduce this strange issue when using 'mc mirror' from AWS s3 to a self-hosted minio. Loads of unwanted [foldername]__XLDIR__ get created and inside each of these is an xl.meta file. Using the minio web console to delete those unwanted XLDIR folders catastrophically deletes the entire folder of the same name. Deleting the folder from the Linux command line on the host seems to have no downside impact, though I've not made a detailed look through any logs.
---
mc information
mc version RELEASE.2023-08-15T23-03-09Z (commit-id=df68f5cf897d30203bfa3003c0882b3f76edcdd7)
Runtime: go1.19.12 linux/amd64
---
minio information
minio/minio:RELEASE.2023-08-16T20-17-30Z
---
environment information
I run minio in a docker container behind a traefik reverse proxy

**Comment by ebozduman** [comment] 2023-08-23 01:07
@v60fan 
I still cannot reproduce the issue with
`mc mirrorr s3/<bucket> myminio/<bucket>`
where `s3` and `myminio` are the aliases to Amazon s3 and MinIO servers.
How big is your data and what is the structure, small or big or mixed objects, ,any other clue to help us to reproduce the issue?

**Comment by harshavardhana** [comment] 2023-08-23 01:11
> I can reproduce this strange issue when using 'mc mirror' from AWS s3 to a self-hosted minio. Loads of unwanted `[foldername] __XLDIR__` get created and inside each of these is an xl.meta file. Using the minio web console to delete those unwanted XLDIR folders catastrophically deletes the entire folder of the same name. Deleting the folder from the Linux command line on the host seems to have no downside impact, though I've not made a detailed look through any logs.

I think it is not unnecessary, it is what is being returned in the list from AWS S3. If there are objects that endswith `/` on your current namespace on AWS S3. `mc mirror` will try to preserve this on MinIO as well.

**Comment by v60fan** [comment] 2023-08-24 15:52
My overall object storage is around 50GB and is mainly smaller objects. Largest object would be about 7GB.

My "workaround" was to sync my AWS s3 to a local drive then sync the local drive into minio. This resulted in none of the XLDIR folders.

**Comment by ebozduman** [comment] 2023-08-24 23:03
@v60fan,

I see. Thank you for the info on your setup.
However, like @harshavardhana said, if there is an object that ends with an \_\_XLDIR\_\_, `mc mirror` will sustain it.
So, this is the expected behavior of `mc mirror`.
