### ISSUE TITLE
mc cp: add auto-resume

### ISSUE THREAD

**Issue by accaldwell** [minio/mc#2046] opened 2017-02-28 05:25 UTC
I use mc as it is the only S3 client that can reliably resume uploads. I frequently make uploads that take multiple days, and the upload connection reliably dies every few hours or so. As is, I have to keep an eye on this, and resume manually. Large/long uploads can require me to manually resume dozens of times for successful completion.

I'd like to request an auto-resume feature. Ideally this would attempt to auto resume transfers after, say 60 seconds (or even better a user-defined resume waiting period).

**Comment by harshavardhana** [comment] 2017-02-28 06:52
`mc cp` already resumes if you retry again.  Rather than having `mc cp` to retry and auto resume` you could easily script this out.. wouldn't it be better @accaldwell - Because it is not an expected behavior for everyone.

**Comment by harshavardhana** [comment] 2017-03-02 04:17
> mc cp already resumes if you retry again. Rather than having mc cp to retry and auto resume` you could easily script this out.. wouldn't it be better @accaldwell - Because it is not an expected behavior for everyone.

Closing this as a non issue / out of scope for the moment.

**Closed by harshavardhana** 2017-03-02 04:17 UTC
Labels: community, wontfix/invalid

**Comment by kapolos** [comment] 2017-07-10 19:29
@harshavardhana `mc cp` does not auto-resume properly if `-r` is used. It only works as you described when the `-r` is not used.

This is my script:

````
#!/bin/bash

until "$@"; do
  echo Tansfer disrupted, retrying in 10 seconds...
  sleep 10
done
````

Every time, it restarts from zero (it's obvious at the end of the screenshot).
![image](https://user-images.githubusercontent.com/10794126/28035847-c4f71044-65be-11e7-9d70-549d93d8ceaf.png)

On the contrary, if I use the `resume` command, it works as intended. I think this should be considered for fixing because it is easier to script it like I did instead of parsing out the resume command each time.

**Comment by David-Development** [comment] 2018-10-08 15:05
@harshavardhana Is there any update on this? I'm encountering some similar issues when using the `mc cp` command. Maybe an additional flag would be useful e.g. `mc cp -r --retry 10` (retry 10 times using exp backoff?). 

@kapolos did you figure out a workaround yet?

**Comment by David-Development** [comment] 2018-10-09 06:45
@harshavardhana Is there any update on this? I'm encountering some similar issues when using the `mc cp` command. Maybe an additional flag would be useful e.g. `mc cp -r --retry 10` (retry 10 times using exp backoff?). 

@kapolos did you figure out a workaround yet?
