### ISSUE TITLE
[build failure] apache thrift migration

### ISSUE THREAD

**Issue by 5paceToast** [minio/mc#2894] opened 2019-09-16 01:46 UTC
## Expected behavior
`go build` produces a binary

## Actual behavior
`go build` fails with:
```
go: git.apache.org/thrift.git@v0.12.0: unknown revision v0.12.0                                                                               go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/toast/aports/testing/minio-client/src/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:         fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Operation timed out       go: error loading module requirements
```

## Steps to reproduce the behavior
1. Download release tarball
2. `export GO111MODULE=on`
3. `go build` (ldflags etc not mentioned for simplicity)

## System information
I'm the package maintainer for mc over at [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=minio-client) and can't bump the version to latest.

## Recommended Solution
I believe adding a new `replace` directive in `go.mod`, as per https://github.com/kubernetes/minikube/issues/5245, but my limited attempts at doing so were unsuccessful.

MinIO is also affected, bug here: https://github.com/minio/minio/issues/8246

**Comment by harshavardhana** [comment] 2019-09-16 02:39
Use go1.13 not go1.12

**Comment by kannappanr** [comment] 2019-09-16 18:30
We require go 1.13 as mentioned above. Closing this issue as working as intended.

**Closed by kannappanr** 2019-09-16 18:30 UTC
