### ISSUE TITLE
Cannot configure a host in docker image minio/mc:RELEASE.2018-07-31T02-28-53Z 

### ISSUE THREAD

**Issue by cfpettersson-svt** [minio/mc#2497] opened 2018-07-31 12:48 UTC
## Expected behaviour

We use the `minio/mc` image in our CI pipelines.

We start by adding the the host with the `mc config host add` command.

The host should be configured and the pipeline can continue.

## Actual behaviour
```
mc: <ERROR> Unable to initialize new config from the provided credentials. The specified bucket is not valid.
```

## Steps to reproduce the behaviour
The following generates the error:
```
docker run -ti --rm minio/mc:RELEASE.2018-07-31T02-28-53Z mc config host add <minio-name> https://<path-to-our-minio>/ ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} S3v4
```

If we use the previous build there is no error:
```
docker run -ti --rm minio/mc:RELEASE.2018-07-13T00-53-22Z mc config host add <minio-name> https://<path-to-our-minio>/ ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} S3v4
```

## mc version
```
Version: 2018-07-31T02:28:53Z
Release-tag: RELEASE.2018-07-31T02-28-53Z
Commit-id: a8c97b467dad6b29caad00fa5ff7712877ffb033
```
## System information
The following info is from the minio browser:

```
VERSION
2017-05-05T01:14:51Z
MEMORY
Used: 2.3 MB | Allocated: 512 GB | Used-Heap: 2.3 MB | Allocated-Heap: 13 MB
PLATFORM
Host: <redacted hostname> | OS: linux | Arch: amd64
RUNTIME
Version: go1.7.5 | CPUs: 2
```

**Comment by nitisht** [comment] 2018-07-31 13:04
This looks like a bug on our end, will fix it ASAP. Closing this as duplicate of #2496

**Closed by nitisht** 2018-07-31 13:04 UTC
