### ISSUE TITLE
copy from local to minio - "<ERROR> Unable to validate source"

### ISSUE THREAD

**Issue by TuxGit** [minio/mc#3613] opened 2021-02-16 19:39 UTC
## Expected behavior
Copy folder from local to minio server
`mcli cp --recursive ./images/ s3repo/public/images/`

## Actual behavior
```mcli: <ERROR> Unable to validate source `./images/`.```

## Steps to reproduce the behavior
`wget https://dl.minio.io/client/mc/release/windows-amd64/mc.exe -O /usr/local/bin/mcli`
see above command.

## mc --version
```
$ mcli --version
mcli version RELEASE.2021-02-14T04-28-06Z
```

## System information

windows 10 + MSYS 2 (or Git-Bash)

**Comment by harshavardhana** [comment] 2021-02-16 19:44
> `` mcli: <ERROR> Unable to validate source `./images/`. ``

can you share `./mcli stat ./images/` ?

**Comment by TuxGit** [comment] 2021-02-16 19:49
> 
> can you share `./mcli stat ./images/` ?

ohh, empty output in console (msys 2)

**Comment by harshavardhana** [comment] 2021-02-16 19:50
> ohh, empty output in console (msys 2)

So it's not accessible by `./mcli`  can you check if Unix stat can access it?

**Comment by TuxGit** [comment] 2021-02-16 19:51
without slashes have output
```
$ mcli stat images
Name      : images\
Date      : 2021-02-03 21:10:26 MSK
Size      : 8.0 KiB
Type      : folder
Metadata  :
  Content-Type       : application/octet-stream
  X-Amz-Meta-Mc-Attrs:
```

**Comment by vadmeste** [comment] 2021-02-16 19:53
@TuxGit could you try with Windows CMD or Powershell ?

**Comment by TuxGit** [comment] 2021-02-16 20:01
> @TuxGit could you try with Windows CMD or Powershell ?

it, works!

`.\mc.exe cp -r .\images\  s3repo/public/`

as I understand, window cli uses validation for back slashes?

I'm like terminals like linux on windows. And would be happy if we could use them =)

**Comment by TuxGit** [comment] 2021-02-16 20:23
>
> So it's not accessible by `./mcli` can you check if Unix stat can access it?

funny but `mcli ls` returns correct listing
```
$ mcli ls ./images/
[2021-02-16 18:04:19 MSK]  21KiB images\Angles.png
[2021-02-16 18:04:19 MSK]  16KiB images\Angles0.png
```

**Comment by bkcsfi** [comment] 2021-04-09 02:36
I have a similar problem, I want to mv all files with a given extension to object store. I have to use find command to make it work

```
C:\>mc --version
mc version RELEASE.2021-03-23T05-46-11Z

C:\>mc stat d:\ABI\mssi\EEXPORT
Name      : EEXPORT\
Date      : 2021-04-08 22:25:37 EDT
Size      : 8.0 KiB
Type      : folder
Metadata  :
  Content-Type       : application/octet-stream
  X-Amz-Meta-Mc-Attrs:

C:\>mc stat d:\ABI\mssi\EEXPORT\test.txt
Name      : test.txt
Date      : 2021-04-08 22:28:53 EDT
Size      : 12 B
Type      : file
Metadata  :
  Content-Type       : text/plain
  X-Amz-Meta-Mc-Attrs:

C:\>mc cp  --insecure d:\ABI\mssi\EEXPORT\*.txt minio2/us-customs/inbox/
mc: <ERROR> Unable to validate source `d:\ABI\mssi\EEXPORT\*.txt`.

C:\>mc mv  --insecure d:\ABI\mssi\EEXPORT\*.txt minio2/us-customs/inbox/
mc: <ERROR> Unable to validate source `d:\ABI\mssi\EEXPORT\*.txt`.

C:\>mc find   d:\ABI\mssi\EEXPORT --name "*.txt"
d:\ABI\mssi\EEXPORT\test.txt

C:\>mc find   d:\ABI\mssi\EEXPORT --name "*.txt" --exec "mc cp --insecure {} minio2/us-customs/inbox/"
`d:/ABI/mssi/EEXPORT/test.txt` -> `minio2/us-customs/inbox/test.txt`
Total: 0 B, Transferred: 12 B, Speed: 333 B/s

C:\>c:mc find   d:\ABI\mssi\EEXPORT --name "*.txt" --exec "mc mv --insecure {} minio2/us-customs/inbox/"
`d:/ABI/mssi/EEXPORT/test.txt` -> `minio2/us-customs/inbox/test.txt`
Total: 0 B, Transferred: 12 B, Speed: 363 B/s
```

**Comment by ebozduman** [comment] 2021-08-08 03:00
Reopening this issue as there is a fix for it, #3666, waiting to be reviewed and merged.

**Closed** 2021-09-22 21:38 UTC
Labels: priority: low, community

**Comment by ebozduman** [comment] 2024-04-02 23:20
@paramazo 
Do you have the latest version of `mc`?
If not, get it and retry your command to check if the issue is reproducible?
If reproducible, then please open up a new issue as this one is `Closed`.

**Comment by ebozduman** [comment] 2024-04-03 09:29
Object storage is not a filesystem.
So, filesystem's `mv` command does not know how to reach the data in MinIO object storage.
That's why some filesystem commands are provided as an `mc` commands, like `mv`, `cp`, `ls`.
You can use those common `mc` commands to work with both filesystem files and objects of object storage.

**Comment by ebozduman** [comment] 2024-04-03 10:45
@paramazo

I have to ask more questions to understand the case; like how do you `move folders from one bucket into another bucket directly on the server (what server are we talking about here?) with mv instead of using the cli tool`?

Sorry if this causes any inconvenience but I have to stop here and kindly invite you to join MinIO Slack channel to ask any MinIO usage questions. Someone from our MinIO Slack community will happily clarify answer, give you the reasons why a certain feature is designed in a certain way, if required, or if there is a better way to achieve a certain goal if any, etc.
Thanks for your understanding.

**Comment by ebozduman** [comment] 2024-04-04 09:07
mc/mcli changed quite a lot since then.
If you think this is a genuine issue, which sounds like it, please file it.
You can also discuss it in Community Slack channel with community members before or after filing it.
