### ISSUE TITLE
mc cp tries to upload >100% of a file then fails

### ISSUE THREAD

**Issue by mcharytoniuk** [minio/mc#2517] opened 2018-08-19 22:48 UTC
## Expected behaviour

`mc copy file host/bucket/file` should just copy the file into the bucket. Like this:

![screen shot 2018-08-20 at 00 42 34](https://user-images.githubusercontent.com/1286785/44313964-f5339d80-a411-11e8-9405-26830a6b7c50.png)

## Actual behaviour

For some files (jpg in my case) it tries to upload the file, it goes up to 500-800% then fails after gateway timeout:

![screen shot 2018-08-20 at 00 41 54](https://user-images.githubusercontent.com/1286785/44313961-e51bbe00-a411-11e8-99b8-194832c19fc7.png)
![screen shot 2018-08-20 at 00 41 59](https://user-images.githubusercontent.com/1286785/44313962-e51bbe00-a411-11e8-92b3-f2439e850845.png)

Other thing is, when piping file contents it works fine and file shows up in web client (I'm using that as a workaround):

![screen shot 2018-08-20 at 00 46 13](https://user-images.githubusercontent.com/1286785/44313984-7a1eb700-a412-11e8-93e8-e82d2425a650.png)

![screen shot 2018-08-20 at 00 47 28](https://user-images.githubusercontent.com/1286785/44313996-a20e1a80-a412-11e8-9809-5ad9b228c2b0.png)

## Steps to reproduce the behaviour

I have installed minio on my server using this Ansible role: https://github.com/atosatto/ansible-minio

I do not know if that matters but I linked mc to `/usr/local/bin/minio-mc` instead of `/usr/local/bin/mc` because I'm also using [Midnight Commander](https://midnight-commander.org/) on a daily basis and there is a name conflict.

It's behind Cloudflare proxy and nginx proxy:

```nginx
server {
  listen 2096 ssl http2;

  ssl_certificate /etc/ssl/certs/uniflow-gunicorn.pem;
  ssl_certificate_key /etc/ssl/private/uniflow-gunicorn.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;

  client_max_body_size 4G;

  server_name (classified :P);

  access_log /home/uniflow-cvision/nginx/gunicorn_access_log;
  error_log /home/uniflow-cvision/nginx/gunicorn_error_log;

  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    # we don't want nginx trying to do something clever with
    # redirects, we set the Host: header above already.
    proxy_redirect off;
    proxy_pass http://127.0.0.1:9091;
  }
}
```

Installation works fine with PHP (https://github.com/thephpleague/flysystem-aws-s3-v3) and Python + Django (https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) adapters. Only `mc` fails to copy files.

I tested it with jpg, png files always with the same result. For example this file doesn't work for me and also produces the above error:

![extremely-cute-kitten](https://user-images.githubusercontent.com/1286785/44314046-01205f00-a414-11e8-87bd-df4486a8b2fa.jpg)

1. ![screen shot 2018-08-20 at 00 58 42](https://user-images.githubusercontent.com/1286785/44314064-3f1d8300-a414-11e8-8d3a-5f4edc5f4481.png)
2. ![screen shot 2018-08-20 at 00 58 08](https://user-images.githubusercontent.com/1286785/44314058-22814b00-a414-11e8-9277-01f1c21224bc.png)

## mc version

```
Version: 2018-03-25T01:22:22Z
Release-tag: RELEASE.2018-03-25T01-22-22Z
Commit-id: da5c19848d1e82a24eddb453b01e83d4a0660de4
```

`minio-mc` was installed via Homebrew, it's the latest version for sure:

![screen shot 2018-08-20 at 00 52 47](https://user-images.githubusercontent.com/1286785/44314023-6e7fc000-a413-11e8-84bd-71a124621a74.png)

## System information

macOS High Sierra 10.13.6

**Comment by kannappanr** [comment] 2018-08-20 01:27
@mcharytoniuk Can you try updating mc to the newer version? Also, can you let us know the behavior if you try connecting to minio directly instead of through a proxy. It might have something to do with the proxy.

**Comment by harshavardhana** [comment] 2018-08-20 02:06
> @mcharytoniuk Can you try updating mc to the newer version? Also, can you let us know the behavior if you try connecting to minio directly instead of through a proxy. It most probably has something to do with the proxy.
> 
> Can you also give us more details about your backend? Is it minio, if yes what version. What mode are you running it on etc.

It looks like `mc` has failed and retried to upload to Minio server, we seem to have a bug when there is a retry and progress bar keeps updating.

**Comment by mcharytoniuk** [comment] 2018-08-20 22:14
@kannappanr my minio version is:

```
VERSION:
  2018-07-23T18:34:49Z
```

It's started like this and behind the above proxy, it's started with supervisord which keeps it running just in case:

![screen shot 2018-08-21 at 00 13 39](https://user-images.githubusercontent.com/1286785/44369573-21652200-a4d7-11e8-9259-30097d6459d0.png)

**Comment by poornas** [comment] 2018-08-22 17:29
@mcharytoniuk , could you upgrade your mc version to the latest release and try again? The latest release is RELEASE.2018-08-18T02-13-04Z. A bug was fixed in one of the previous releases that prevents progress showing >100%.

**Comment by poornas** [comment] 2018-08-23 16:51
@mcharytoniuk, did you encounter the same issue after upgrading to latest mc?

**Comment by mcharytoniuk** [comment] 2018-08-24 08:42
@poornas Sorry for no response for that long, I'll check in the weekend and let you know.

**Comment by mcharytoniuk** [comment] 2018-08-26 09:51
@poornas I built `mc` from source (btw it doesn't compile with go 1.11, I had to use go 1.10 - but it seems to be a Go issue):

![screen shot 2018-08-26 at 11 49 22](https://user-images.githubusercontent.com/1286785/44626952-1c183500-a926-11e8-9373-6c628fe2f17b.png)

Progress bar is ok now, but upload immediately crashes:

![screen shot 2018-08-26 at 11 49 59](https://user-images.githubusercontent.com/1286785/44626977-36eaa980-a926-11e8-9f51-2ae806083816.png)

With any other type of adapter (php, python) and `mc pipe | ...` it's ok though.

**Comment by poornas** [comment] 2018-08-27 02:52
It seems to be an issue related to proxy. mc version 2018-03-25T01:22:22Z and above copied the png file above correctly. will try to repro the issue with proxy.

**Comment by kannappanr** [comment] 2018-08-27 04:13
@mcharytoniuk Are you seeing this issue, if you skip the proxy and talk directly to `minio`? 

Also, can you enable HTTP trace on the server. You can start minio using the following command `MINIO_HTTP_TRACE=/dev/stdout minio server --address :9091 /home/minio/data` You can also run the `mc cp` command with `--debug` option turned and paste the output related to this command here.

You can also then run `mc pipe` with the debug flag turned on and paste the output here.

Also, what if you rename the `jpg` file to say `.txt` file on the source and try this `mc cp` command, do you still see the failure?

Also, can you give us more information about this proxy, the name, version and any config file for us to repro the issue?

**Comment by mcharytoniuk** [comment] 2018-08-27 05:14
@kaankabalak sure, I'll try those in the next few days and I'll give you some feedback.

**Comment by deekoder** [comment] 2018-08-29 19:26
hi @mcharytoniuk  were you able to run this with the trace setting on? That will help us a great deal.

**Comment by deekoder** [comment] 2018-11-01 21:58
hi @mcharytoniuk can you post it with the trace settings on. Until then we are not able to exactly repro your issue. Tell us more about the proxy. I will close this as a working as intended (aka not repro) for now. Please reactivate if you have all this info to help us out.

**Closed by deekoder** 2018-11-01 21:58 UTC
Labels: community, priority: medium, triage, working as intended
