### ISSUE TITLE
Unable to list public S3 buckets

### ISSUE THREAD

**Issue by realies** [minio/mc#2778] opened 2019-05-24 00:05 UTC
Noticed that when using `aws s3 ls s3://my-public-bucket --no-sign-request` I can list it successfully, but whenever `mc ls s3/my-public-bucket` when there is no `accessKey` and `secretKey` properties in the s3 config object, the client dies with `mc: <ERROR> Unable to stat `s3/my-public-bucket`. Head https://my-public-bucket.s3.dualstack.us-east-1.amazonaws.com/: 301 response missing Location header.`

The last message when debugging `mc` is
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>my-public-bucket.s3.dualstack.eu-west-1.amazonaws.com</Endpoint><Bucket>my-public-bucket</Bucket><RequestId>xxx</RequestId><HostId>xxx/mRq62r8ZmgEL4Gx6hoSABJCZY=</HostId></Error>
```
which is a different endpoint to the one `aws s3` calls when listing (`my-public-bucket.s3.amazonaws.com`). The later endpoint is accessible without any authorisation, wonder if that could be achieved by the minio client?

**Comment by harshavardhana** [comment] 2019-05-24 00:28
mc requires access to getBucketLocation() API to figure out the right region, looks like you don't have that permission and of course your aws CLI has region configured.

**Comment by realies** [comment] 2019-05-24 01:53
@harshavardhana, aws CLI is not configured with a region, it initiates a GET request to `https://my-public-bucket.s3.amazonaws.com` without defining a region.

**Comment by harshavardhana** [comment] 2019-05-24 02:27
Can you provide --debug output from the AWS cli ?

**Comment by realies** [comment] 2019-05-26 05:02
Not having access to do so at the moment. Is it possible to replicate by the above description alone?

**Comment by kannappanr** [comment] 2019-05-26 05:19
@realies We have reproduced the issue. Will send a PR to handle this issue

**Comment by kannappanr** [comment] 2019-06-05 22:48
Once https://github.com/minio/minio-go/pull/1117 is released and added to `go.mod` in `mc`, this issue will be resolved.

**Comment by kannappanr** [comment] 2019-06-07 23:20
Please try `mc.RELEASE.2019-06-07T00-01-32Z` . Closing this issue as fixed. Please feel free to re-open the issueif you feel otherwise

**Closed by kannappanr** 2019-06-07 23:20 UTC
Labels: community, priority: medium
