### ISSUE TITLE
Server expects client requests with 'admin' API version 'v2', found 'v1', please upgrade the client to latest releases.

### ISSUE THREAD

**Issue by ThalesC** [minio/mc#2977] opened 2019-12-02 18:22 UTC
## Expected behavior
Manage users and policies.
## Actual behavior
Returns the api version error and does nothing.
## Steps to reproduce the behavior
- Download minio browser from source (https://github.com/minio/minio/tree/master/browser)
- Edit app/index.html to enable IOS web app (works like a charm)
- Add SSL to certs/ and host with Nginx (works fine too)
- Install mc binary (wget https://dl.min.io/client/mc/release/linux-amd64/mc)
- Try and use mc to manage users and policies

Using mc with minio binary works, but I am trying to work with the source code to add IOS web app support (add meta tags to app/index.html)
## mc version
mc version RELEASE.2019-10-09T22-54-57Z

## System information

Linux Lite VM - quad core - 4GB RAM

**Comment by harshavardhana** [comment] 2019-12-02 18:28
MinIO master is incompatible with released mc, use released MinIO instead or upgrade your mc to use master as well

Closing this issue as working as intended.

**Closed by harshavardhana** 2019-12-02 18:28 UTC
Labels: wontfix/invalid

**Comment by ThalesC** [comment] 2019-12-02 18:52
Thanks for the heads up!
