### ISSUE TITLE
MC_HOSTS_* broken?

### ISSUE THREAD

**Issue by skob** [minio/mc#2779] opened 2019-05-24 08:42 UTC
seems like #2442 return :(

## Expected behaviour

Look for documentation relating to MC_HOSTS_* environment variable which allows passing configuration to mc via the environment rather then its configuration files.

Find documentation.

## Actual behaviour

It's not there.

I've looked everywhere. I found reference to it in the code and I have it working using the current stable release. I'd be happy to assist but would need someone who understands it properly to review my submission

**Comment by skob** [comment] 2019-05-24 08:44
sorry will reopen

**Comment by nitisht** [comment] 2019-05-24 09:51
Documentation is available here https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#specify-host-configuration-through-environment-variable @skob 

Closing this as working as intended. Feel free to join us on slack for more such questions

**Closed by nitisht** 2019-05-24 09:51 UTC
