### ISSUE TITLE
"mc watch" issues 350 syscalls/sec while doing nothing

### ISSUE THREAD

**Issue by occasionallydavid** [minio/mc#3671] opened 2021-03-28 22:30 UTC
## Expected behavior

Watch completely sleeps using energy efficient edge-triggered notification mechanism like inotify/dnotify

## Actual behavior

On a quad core machine, watch issues around 350 syscalls per second, burning CPU, wasting battery, and stealing time from other jobs. Setting GOMAXPROCS=1 reduces this to around 220/s

## Steps to reproduce the behavior

Run `mc watch` and wait for it to reach an 'idle' state on a small folder.

Observe powertop output and `perf trace -p $(pidof mc) 2>&1 | pv -l >/dev/null`

## mc --version

mc version RELEASE.2021-03-23T05-46-11Z

## System information

Linux localhost 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by harshavardhana** [comment] 2021-03-29 02:46
> Run `mc watch` and wait for it to reach an 'idle' state on a small folder.

Not sure what this means - Just tested this locally 

```
~ mc watch pkg
```

```
~ perf trace -p $(pidof mc) 2>&1 | pv -l /dev/null
0.00  0:00:00 [0.00 /s] [<=>
```

I see 0 syscalls are you sure you don't have any other operation happening on the folders?

Can you provide a more precise reproducer?

**Comment by occasionallydavid** [comment] 2021-03-29 04:44
Somehow I confused `mc watch` with `mc mirror`. The command exhibiting the bad behaviour is `mc mirror`

The exact set of commands used:

```
$ mkdir foo
$ touch foo/x
$ mc mirror foo sbox/test/foo
```

Shortly a progress bar will appear:

![image](https://user-images.githubusercontent.com/62972099/112787607-cb729680-9050-11eb-8ace-2fc1716694af.png)

This progress bar appears to reveal nothing is happening and that the tool is idle. Above this is referred to 'an idle state'.

Inspecting the process with `powertop` reveals it is waking 54 times/sec:

![image](https://user-images.githubusercontent.com/62972099/112787768-38862c00-9051-11eb-86a8-ef35093a9e56.png)

Inspecting the process with `perf` reveals it is repeatedly polling with the same pattern of syscalls across a pool of threads:

![image](https://user-images.githubusercontent.com/62972099/112787979-ba765500-9051-11eb-8c4c-0b0da6e1c811.png)

**Comment by ebozduman** [comment] 2021-04-20 20:38
@occasionallydavid,

I am looking into reproducing the issue.

> Somehow I confused mc watch with mc mirror. The command exhibiting the bad behaviour is mc mirror

Obviously you meant "**mc mirror --watch** \<source\> \<destination\>"

**Comment by ebozduman** [comment] 2021-04-22 16:31
@occasionallydavid,

This is how `"rjeczalik/notify"` notification package works and there is no better alternative at this point.
Closing as "works as intended.

**Closed by ebozduman** 2021-04-22 16:31 UTC
Labels: community, working as intended
