### ISSUE TITLE
mc rm won't remove file

### ISSUE THREAD

**Issue by CompuRoot** [minio/mc#2836] opened 2019-07-24 14:11 UTC
## Expected behavior
When one run `mc rm storage/bucket/file` then it should remove that file
When one run `mc stat storage/bucket/file` then `mc` should show stat info

## Actual behavior
`mc` return error for both listed above commands.

## Steps to reproduce the behavior
1. `mc cp ./file storage/bucket` # copied successfully
2.  `mc ls storage/bucket/file` # listed copied file successfully
3.  `mc stat storage/bucket/file`  
Return error: 
> mc: <ERROR> Unable to stat 'storage/bucket/file'. Target 'storage/bucket/file' not found.

4.  `mc rm storage/bucket/file`   
Return error:  
> mc: <ERROR> Failed to remove 'storage/bucket/file'. Target 'storage/bucket/file' not found.

## mc version
Version: 2019-07-24T02:55:56Z
Release-tag: RELEASE.2019-07-24T02-55-56Z
Commit-id: 67dbada736f80b9283df5cba4b526b806eb1968e

## System information
Server: 
    Version
    2019-07-24T02:02:23Z
    Memory
    Used: 3.9 MB | Allocated: 41 MB | Used-Heap: 3.9 MB | Allocated-Heap: 12 MB
    Platform
    Host: SomeHost | OS: windows | Arch: amd64
    Runtime
    Version: go1.12.5 | CPUs: 4

<hr>

## Workaround:
To be able to delete some file from `minio` storage, one should use for some reason `--recursive` option with  `rm` commands even if it is a single file located in a root of bucket.

The same is with `stat` command, to be able to show object metadata, command `stat` must be issued with `-r` option.

P.S.
Another way to work around this issue on Windows until this would be fixed, is to use @vadmeste  finding, - one should use backslash (`\`) in place of forward slash (`/`) like:
`mc rm play\mytestbucket\some.txt `
`mc stat play\mytestbucket\some.txt `

**Comment by vadmeste** [comment] 2019-07-24 14:25
@CompuRoot can you test with Minio play server ? 

```
$ mc mb play/mytestbucket
$ mc cp file play/mytestbucket/file
$ mc stat play/mytestbucket/file
```

(play alias is already configured, you don't have to do something to configure it)

**Comment by CompuRoot** [comment] 2019-07-24 14:35
@vadmeste 

Tried your suggestion, unfortunately - the same result: 
`mc stat play/mytestbuck/some.txt `
`mc: <ERROR> Unable to stat 'play/mytestbuck/some.txt'. The specified bucket does not exist.`

but with option `-r` it clearly there:

```
#mc stat -r play/mytestbucket/some.txt

Name      : some.txt
Date      : 2019-07-24 10:33:12 EDT
Size      : 4 B
ETag      : aefcd320422617869da103b5eed7041c
Type      : file
Metadata  :
  Content-Type: text/plain
Encrypted :
  X-Amz-Server-Side-Encryption: AES256
```

**Comment by vadmeste** [comment] 2019-07-24 15:20
@CompuRoot I confirm this is happening under Windows, but it works with anti-slash instead.

`mc rm play\mytestbucket\some.txt` (or stat) should work.

But still this still needs to be fixed

**Comment by CompuRoot** [comment] 2019-07-24 15:39
@vadmeste 
>But still this still needs to be fixed
Agree. Actually Windows can work with both, forward and back slashes, but for some reason `minio` can't.

**Comment by kannappanr** [comment] 2019-07-25 23:46
Duplicate of #2772 . #2774 Should fix this issue.

**Comment by kannappanr** [comment] 2019-07-26 00:45
@CompuRoot Can you please test the latest master and let us know if you still see this issue?

**Comment by kannappanr** [comment] 2019-07-26 20:56
#2774 has been merged, closing this issue as fixed. Please feel free to open this issue if you feel otherwise.

**Closed by kannappanr** 2019-07-26 20:56 UTC
Labels: community, priority: medium

**Comment by CompuRoot** [comment] 2019-07-29 23:08
@kannappanr 

>Can you please test the latest master and let us know if you still see this issue?

I  re-downloaded minio server (from official page [here](https://dl.min.io/server/minio/release/windows-amd64/minio.exe)) and `mc` utility (from [here](https://dl.min.io/client/mc/release/windows-amd64/mc.exe))  and tested it again, but it looks like described behavior is still the same, neither one `rm` nor `stat` commands  won't work correctly without workarounds.

**Comment by kannappanr** [comment] 2019-07-29 23:10
@CompuRoot You need to build it yourself or wait for the next release. It is not part of the release yet.
