### ISSUE TITLE
Minio client fails to copy local files with extended attributes to remote Minio server

### ISSUE THREAD

**Issue by gnfurlong** [minio/mc#2388] opened 2018-02-10 22:51 UTC
## Expected behaviour
Given user has a file with Linux extended attributes, the user can successfully upload the file using Minio client to a target Minio server (using mcli cp or mcli mirror)

## Actual behaviour
Upload fails with error message "Unexpected EOF".

## Steps to reproduce the behaviour

echo "Some test data" >> testfile
setfattr -n user.example -v "Some value" testfile
mcli cp ./testfile ${minioServerName}/${bucketName}/testfile

## mc version
Release-tag: DEVELOPMENT.2018-02-10T18-01-06Z
Commit-id: d9663e5d96d5f32725867167de2a0403704ae537

## System information
Client
Os: ArchLinux
Package: https://aur.archlinux.org/packages/minio-client

## Minio Server information
Docker image: minio/minio:latest

Version: 2017-12-28T01:21:00Z
Release-Tag: RELEASE.2017-12-28T01-21-00Z
Commit-ID: 545a9e4a820e8432a864398e6fbd2bf46c4fc917

**Comment by poornas** [comment] 2018-02-12 19:36
@gnfurlong, can you download the official mc client from https://dl.minio.io/client/mc/release/ and let us know if you see the same issue? 

It would be super helpful if you could turn the --debug flag on and paste it here so we can isolate the issue.
```
mc --debug cp ./testfile ${minioServerName}/${bucketName}/testfile
```

**Comment by gnfurlong** [comment] 2018-02-15 13:03
@poornas I downloaded the official mc client from https://dl.minio.io/client/mc/release/linux-amd64/mc

The upload seems to be failing with the below error message.

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/myTestFileWithXAttrs</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>

I've attached the full log below (with domain names/host names/access key replaced).
[minio-debug.log](https://github.com/minio/mc/files/1727704/minio-debug.log)

**Comment by poornas** [comment] 2018-02-15 19:31
@gnfurlong, looks like nginx is filtering/adding headers - could you set server side trace on and attach that log as well?

**Comment by poornas** [comment] 2018-02-21 23:49
@gnfurlong, could you add the server side trace? Thanks

**Comment by pryorda** [comment] 2018-02-23 04:33
https://github.com/minio/minio/issues/5571 is a redundant ticket to this.

**Comment by pryorda** [comment] 2018-02-23 04:38
@poornas here is mine
```
Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:132:cmd.checkRequestAuthType()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:611:cmd.objectAPIHandlers.NewMultipartUploadHandler()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:55:cmd.(objectAPIHandlers).NewMultipartUploadHandler-fm()
       4: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:605:cmd.rateLimit.ServeHTTP()
       7: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:563:cmd.pathValidityHandler.ServeHTTP()
       8: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:502:cmd.httpStatsHandler.ServeHTTP()
       9: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      10: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
      11: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      12: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:219:cmd.redirectHandler.ServeHTTP()
      13: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:277:cmd.minioReservedBucketHandler.ServeHTTP()
      14: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:246:cmd.cacheControlHandler.ServeHTTP()
      15: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:347:cmd.timeValidityHandler.ServeHTTP()
      16: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      17: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
      18: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:453:cmd.resourceHandler.ServeHTTP()
      19: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:244:cmd.authHandler.ServeHTTP()
      20: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:133:cmd.reservedMetadataHandler.ServeHTTP()
      21: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:111:http.(*Server).Start.func1()
      22: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
      23: /opt/go/src/net/http/server.go:2619:http.serverHandler.ServeHTTP()
      24: /opt/go/src/net/http/server.go:1801:http.(*conn).serve()
[2018-02-23T04:36:30.831390635Z] [ERROR] {"method":"POST","reqURI":"/general/VMware-VMvisor-Installer-201701001-4887370.x86_64.iso?uploads=","header":{"Authorization":["AWS4-HMAC-SHA256 Credential=GONEGONE/20180223/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-meta-user.xdg.origin.url;x-amz-meta-user.xdg.referrer.url, Signature=0bfc5bc0f47488f9b6b1f65bf8b8226f2afd57973b8746f6fd7e2e34f76f611f"],"Connection":["close"],"Content-Length":["0"],"Content-Type":["application/x-iso9660-image"],"Host":["example.com"],"User-Agent":["Minio (linux; amd64) minio-go/4.0.7 mc/2018-02-09T23:07:36Z"],"X-Amz-Content-Sha256":["UNSIGNED-PAYLOAD"],"X-Amz-Date":["20180223T043630Z"]}} (Signature does not match)

```

**Comment by pryorda** [comment] 2018-02-23 05:30
See my comment on my other ticket it shows you can resolve the issue with ignore_invalid_headers off;

**Comment by poornas** [comment] 2018-02-23 06:11
thanks @pryorda, looks like awscli does not support xattr from my search (there is a feature request no.1833 that was not implemented)

**Comment by poornas** [comment] 2018-02-24 23:04
@gnfurlong , you might want to use @pryorda 's suggestion to add  ignore_invalid_headers off;   to your nginx configuration and see if mc cp command works for you

**Comment by deekoder** [comment] 2018-02-28 22:55
From our testing, we are not able to reproduce this @gnfurlong  and @pryorda .  We will close it. If you  are still seeing this on your end (with the latest mc) please reactivate.

**Closed by deekoder** 2018-02-28 22:55 UTC
Labels: priority: medium, working as intended
