### ISSUE TITLE
/mc config host add s3  <internal docker minio cluster>  <access key> <secret key> doesnt work with new mc client released on 7/31   .. 6/30 client works

### ISSUE THREAD

**Issue by joetristano** [minio/mc#2501] opened 2018-08-01 16:31 UTC
## Expected behaviour
Added `s3` successfully.

## Actual behaviour
mc: <ERROR> Unable to initialize new config from the provided credentials. The specified bucket is not valid.

## Steps to reproduce the behaviour
docker base image of fedora 24
From Dockerfile
RUN wget the latest minio client 
## mc version
- (paste output of `mc version`)
  2018-07-31T02:28:53Z

## System information
MacOS 10.13.5  running  Docker Version 18.03.1-ce-mac65 (24312)

**Comment by kannappanr** [comment] 2018-08-01 20:45
@joetristano This looks like a duplicate of #2496 We have a fix in master already. Will try to make a release in a day or two.

**Comment by kannappanr** [comment] 2018-08-03 15:47
@joetristano Closing this issue as fixed as the current mc release has this fix.

**Closed by kannappanr** 2018-08-03 15:47 UTC
Labels: community, duplicate, priority: medium
